import React,{useCallback,useEffect,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {FaComments,FaSearch,FaShieldAlt,FaTrash,FaUsers} from 'react-icons/fa';
import {adminDeleteConversation,getAdminConversations} from '../../api/chatApi';

export default function AdminChat(){
 const navigate=useNavigate(),[rows,setRows]=useState([]),[q,setQ]=useState(''),[error,setError]=useState(''),[deleting,setDeleting]=useState(null);
 const load=useCallback(async()=>{try{setRows(await getAdminConversations(q));setError('')}catch(e){setError(e?.response?.data?.message||'Chat management could not be loaded.')}},[q]);
 useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[load]);
 const remove=async conversation=>{if(!window.confirm(`Permanently delete "${conversation.name}"? All messages, members, notifications, and discussion links will be removed for everyone. This cannot be undone.`))return;setDeleting(conversation.id);setError('');try{await adminDeleteConversation(conversation.id);setRows(current=>current.filter(x=>x.id!==conversation.id))}catch(e){setError(e?.response?.data?.message||'Conversation could not be deleted.')}finally{setDeleting(null)}};
 return <main className="chat-admin"><header><div><small>ADMINISTRATION</small><h1><FaShieldAlt/> Chat Management</h1><p>Monitor conversation metadata, membership, activity, and business context. Administrators can permanently remove group chats and contextual discussions.</p></div></header><label><FaSearch/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search conversations and discussions"/></label>{error&&<p className="chat-error">{error}</p>}<section><table><thead><tr><th>Conversation</th><th>Type / Context</th><th>Owner</th><th>Members</th><th>Messages</th><th>Last activity</th><th>Actions</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><strong>{x.name}</strong><small>#{x.id} · {x.status}</small></td><td>{x.type}<small>{x.context_type&&`${x.context_type} #${x.context_id}`}</small></td><td>{x.created_by_name}</td><td><FaUsers/> {x.member_count}</td><td><FaComments/> {x.message_count}</td><td>{x.last_message_at||'No activity'}</td><td><div className="chat-admin-actions"><button onClick={()=>navigate(`/dashboard/chat?conversation=${x.id}`)}>Open</button>{['group','contextual'].includes(x.type)&&<button className="danger" disabled={deleting===x.id} onClick={()=>remove(x)}><FaTrash/> {deleting===x.id?'Deleting...':'Delete'}</button>}</div></td></tr>)}</tbody></table>{!rows.length&&!error&&<p className="chat-empty">No conversations found.</p>}</section></main>
}