import {useEffect,useRef,useState} from 'react';
import {FaComments,FaPaperPlane,FaRobot,FaTimes} from 'react-icons/fa';
import {useLocation,useNavigate} from 'react-router-dom';
const guide=[
 {keys:['submission','submissions'],answer:'Open Dashboard, choose Submissions, and open a record. Use Discuss in the header for the submission-specific conversation.',route:'/dashboard#records'},
 {keys:['candidate','resume'],answer:'Candidates are under Dashboard > Candidates. Open a candidate for overview, reports, documents, resume, job matches, and the contextual Discuss action.',route:'/dashboard/candidates'},
 {keys:['recruiter','recruiting'],answer:'Recruiting records are under Dashboard > Recruiting. Open a recruiter or application record, then use Discuss for a record-linked conversation.',route:'/dashboard/recruiting'},
 {keys:['employee','profile','attendance'],answer:'Employee Status and My Profile contain identity, performance, and attendance information. Use the header Discuss action to collaborate on the current profile.',route:'/dashboard/employee-status'},
 {keys:['job','jobs'],answer:'Jobs are managed under Dashboard > Jobs. Open a job and select Discuss to reuse its job discussion.',route:'/dashboard/jobs'},
 {keys:['vendor','client'],answer:'Vendor and client resources are available from the dashboard sidebar according to your permissions. Their detail pages support contextual discussions.',route:'/dashboard/vendors'},
 {keys:['notification','bell'],answer:'The header bell shows unread messages and discussion activity. Select an item to open its exact conversation, or open the full Notifications page.',route:'/dashboard/notifications'},
 {keys:['group','team'],answer:'Open Chat, select +, choose Group / Team, enter a name, select members, and create it. Owners and group admins can add more members.',route:'/dashboard/chat'},
 {keys:['chat','message','discussion'],answer:'Chat contains direct conversations, group/team chats, and business-record discussions. Your messages appear on the right; teammate messages appear on the left. Hover a message for Reply, Edit, or Delete options.',route:'/dashboard/chat'},
 {keys:['admin','management'],answer:'Authorized administrators can open Chat Management to review conversation metadata, context, membership, and activity.',route:'/dashboard/admin/chat'},
 {keys:['permission','access'],answer:'Access is controlled by position and user permissions. Administrators manage resources and actions in the Permission Matrix.',route:'/dashboard/permissions'},
];
const answer=q=>{const value=q.toLowerCase();const match=guide.find(item=>item.keys.some(k=>value.includes(k)));return match||{answer:'I can help with Dashboard, submissions, candidates, recruiters, jobs, employees, profiles, attendance, permissions, chats, groups, discussions, notifications, and Chat Management. Ask how to use one of these areas.'};};
export default function ApplicationAssistant(){const location=useLocation(),navigate=useNavigate(),[open,setOpen]=useState(false),[text,setText]=useState(''),[messages,setMessages]=useState([{role:'assistant',text:'Hello! I am the E2E application assistant. How can I help you use this page?'}]),end=useRef(null);useEffect(()=>{end.current?.scrollIntoView({behavior:'smooth'});return undefined},[messages,open]);const send=e=>{e.preventDefault();const q=text.trim();if(!q)return;const result=answer(q);setMessages(v=>[...v,{role:'user',text:q},{role:'assistant',text:result.answer,route:result.route}]);setText('')};return <aside className={`app-assistant ${open?'open':''}`}><button className="app-assistant-launch" onClick={()=>setOpen(v=>!v)} aria-label={open?'Close application assistant':'Open application assistant'}>{open?<FaTimes/>:<FaRobot/>}</button>{open&&<section role="dialog" aria-label="E2E application assistant"><header><span><FaRobot/></span><div><strong>E2E Assistant</strong><small>Application help · Current page: {location.pathname}</small></div><button onClick={()=>setOpen(false)}><FaTimes/></button></header><div className="app-assistant-messages">{messages.map((m,i)=><article key={i} className={m.role}><p>{m.text}</p>{m.route&&<button onClick={()=>{navigate(m.route);setOpen(false)}}>Open this area</button>}</article>)}<div ref={end}/></div><div className="app-assistant-suggestions"><button onClick={()=>setText('How do discussions work?')}>Discussions</button><button onClick={()=>setText('How do group chats work?')}>Group chats</button><button onClick={()=>setText('Where are submissions?')}>Submissions</button></div><form onSubmit={send}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Ask about E2E Tracking..." aria-label="Ask the application assistant"/><button disabled={!text.trim()}><FaPaperPlane/></button></form><footer><FaComments/> Answers stay inside the application.</footer></section>}</aside>}