import {useEffect,useMemo,useRef,useState} from "react";
import {FaArrowLeft,FaComments,FaExternalLinkAlt,FaPaperPlane,FaRobot,FaSearch,FaThLarge,FaTimes} from "react-icons/fa";
import {useLocation,useNavigate} from "react-router-dom";
import {usePermissions} from "../../auth/PermissionContext";

const catalog={
 dashboard:{label:"Dashboard",keys:["dashboard","home","overview"],summary:"The Dashboard centralizes business activity, workforce performance, operations, expiring documents and record analytics.",actions:[["Open Dashboard","/dashboard"],["Overview","/dashboard#overview"],["Workforce","/dashboard#workforce"],["Operations","/dashboard#operations"],["Records","/dashboard#records"]],related:["attendance","candidates","recruiting","bench_sales"]},
 recruiting:{label:"Recruiting",keys:["recruiting","recruiter","applications"],summary:"Manage recruiter applications, candidate activity, submission progress and recruiter-specific records.",actions:[["Open Recruiting","/dashboard/recruiting"],["Search Recruiters","search:recruiter"]],related:["candidates","jobs","bench_sales"]},
 bench_sales:{label:"Bench Sales",keys:["bench sales","submission","submissions"],summary:"Review consultant submissions, sales activity, performance and detailed submission records.",actions:[["Open Bench Sales","/dashboard/bench-sales"],["Performance","/dashboard/bench-sales/performance"],["Dashboard Records","/dashboard#records"]],related:["hot_list","jobs","candidates"]},
 hot_list:{label:"Hot List",keys:["hot list","hotlist"],summary:"View and manage actively marketed consultants and their latest availability details.",actions:[["Open Hot List","/dashboard/hotlist"]],related:["bench_sales","candidates","jobs"]},
 jobs:{label:"Jobs",keys:["job","jobs","requirement"],summary:"Review job requirements, matching candidates and job-specific details.",actions:[["Open Jobs","/dashboard/jobs"],["Search Jobs","search:job"]],related:["candidates","recruiting","prime_vendors"]},
 prime_vendors:{label:"Prime Vendors",keys:["vendor","vendors","prime vendor"],summary:"Manage prime-vendor organizations, contacts and linked business records.",actions:[["Open Prime Vendors","/dashboard/vendors"]],related:["clients","jobs","vendor_onboarding"]},
 clients:{label:"Clients",keys:["client","clients"],summary:"View and maintain client organization records available to your role.",actions:[["Open Clients","/dashboard/clients"]],related:["prime_vendors","jobs"]},
 candidates:{label:"Candidates",keys:["candidate","candidates","resume","profile"],summary:"Candidate profiles include personal data, resumes, documents, reports, activity, job matches and contextual discussions.",actions:[["Open Candidates","/dashboard/candidates"],["Search Candidates","search:candidate"]],related:["document_reminders","jobs","candidate_onboarding"]},
 document_reminders:{label:"Document Reminders",keys:["document","reminder","h1b","perm","i-140"],summary:"Monitor H1B, PERM and I-140 dates, edit schedules, preview documents, send reminders and manage the organization reminder mailbox.",actions:[["Open Reminders","/dashboard/document-reminders"]],related:["candidates","notifications"]},
 attendance:{label:"Attendance Management",keys:["attendance","leave","holiday","payslip","payroll"],summary:"Manage daily attendance, monthly summaries, employee payslips, leave approvals, employee leave, holidays and authorized WFH access.",actions:[["Open Attendance","/dashboard/attendance"],["Monthly Summary","/dashboard/attendance?assistant=monthly"],["Payslips","/dashboard/attendance?assistant=payslips"],["Leave Approvals","/dashboard/attendance?assistant=approvals"],["Holidays","/dashboard/attendance?assistant=holidays"]],related:["employees","profile","dashboard"]},
 employees:{label:"Employee Status",keys:["employee","employees","employee status"],summary:"Review employee identity, company assignment, profile, attendance and performance information.",actions:[["Open Employee Status","/dashboard/employee-status"],["Search Employees","search:employee"]],related:["attendance","users","profile"]},
 profile:{label:"My Profile",keys:["my profile","profile","my attendance"],summary:"See your personal employee profile, performance, attendance and company identity information.",actions:[["Open My Profile","/dashboard/my-profile"],["My Attendance","/dashboard/my-profile#profile-attendance"],["Company Identity","/dashboard/my-profile#profile-identity"]],related:["attendance","notifications"]},
 users:{label:"User Management",keys:["user","users","login"],summary:"Administrators manage company logins, roles, status and employee assignments here.",actions:[["Open User Management","/dashboard/users"]],related:["permissions","employees"]},
 permissions:{label:"Permissions",keys:["permission","permissions","access","role"],summary:"Configure role defaults and user-specific resource permissions, actions and data scope.",actions:[["Open Permissions","/dashboard/permissions"]],related:["users","resources","positions"]},
 chat:{label:"Enterprise Chat",keys:["chat","message","discussion","group","team"],summary:"Use direct messages, groups, teams and contextual record discussions with unread tracking and attachments.",actions:[["Open Chat","/dashboard/chat"],["Notifications","/dashboard/notifications"]],related:["chat_notifications","chat_admin"]},
 chat_notifications:{label:"Notifications",keys:["notification","notifications","unread","bell"],summary:"Review unread messages, mentions, replies and resource-discussion activity, then open the related conversation.",actions:[["Open Notifications","/dashboard/notifications"],["Open Chat","/dashboard/chat"]],related:["chat"]},
 chat_admin:{label:"Chat Management",keys:["chat admin","chat management"],summary:"Authorized administrators can audit conversations, membership, contexts and chat activity.",actions:[["Open Chat Management","/dashboard/admin/chat"]],related:["chat","permissions"]},
 training:{label:"Training",keys:["training","learning"],summary:"Manage and review training-related records available to your role.",actions:[["Open Training","/dashboard/training"]],related:["candidates","employees"]},
 candidate_onboarding:{label:"Candidate Onboarding",keys:["candidate onboarding","onboarding"],summary:"Manage candidate onboarding workflows and required information.",actions:[["Open Candidate Onboarding","/dashboard/candidate-onboarding"]],related:["candidates","w2_forms"]},
 vendor_onboarding:{label:"Vendor Onboarding",keys:["vendor onboarding"],summary:"Manage vendor onboarding details and associated workflows.",actions:[["Open Vendor Onboarding","/dashboard/vendor-onboarding"]],related:["prime_vendors"]},
 w2_forms:{label:"W2 Forms",keys:["w2","w-2","tax form"],summary:"Review secure W2 information submissions and their processing status.",actions:[["Open W2 Forms","/dashboard/w2-forms"]],related:["candidate_onboarding","candidates"]},
 positions:{label:"Positions",keys:["position","positions"],summary:"Maintain the organization position catalog used by employees, users and permissions.",actions:[["Open Positions","/dashboard/positions"]],related:["permissions","users"]},
 resources:{label:"Resources",keys:["resource","resources","modules"],summary:"Maintain the centralized resource catalog that controls dashboard pages and capabilities.",actions:[["Open Resources","/dashboard/resources"]],related:["permissions","positions"]}
};
const details={
 dashboard:["Overview cards summarize the latest business totals and operational health.","Workforce analytics compares employee and recruiter performance by period.","Operations highlights important work such as expiring documents and active processes.","Records contains searchable, sortable and exportable submissions, candidates, interviews and placements."],
 recruiting:["Review recruiter-owned applications and candidate activity.","Open an application to inspect its complete record and permitted actions.","Use the Navbar search to locate recruiters or records quickly.","Contextual Discuss keeps conversation connected to the record."],
 bench_sales:["Track consultant submissions, vendors, clients, rates and current status.","Open detailed submission records and recruiter performance.","Filter and search the list to find a consultant or submission.","Related Hot List and Jobs pages support the same sales workflow."],
 hot_list:["Shows consultants currently available for marketing.","Review contact, technology and availability information.","Use the related Bench Sales workflow to manage submissions."],
 jobs:["Review job requirements, technology, location and status.","Open job details and view matching candidates where available.","Use Candidates and Vendors for the connected placement workflow."],
 prime_vendors:["Stores prime-vendor organizations and contact information.","Open a vendor record for full details and related activity.","Vendor Onboarding captures new vendor information."],
 clients:["Stores client organizations available to your role.","Use these records when reviewing jobs, vendors and submissions.","Visibility and available actions follow your permissions."],
 candidates:["Profiles contain personal and professional candidate information.","Documents includes immigration files, target dates and reminders.","Reports and Activity shows related workflow history.","Skills and Resume supports candidate evaluation.","Job Matches connects a candidate with suitable requirements."],
 document_reminders:["Tracks H1B expiry dates, PERM filing windows and I-140 priority dates.","Filter by candidate, document type, status, date or remaining days.","Preview documents, inspect stored details, edit schedules, send immediately or disable reminders.","Admin can configure one encrypted organization sender and recipient for manual and scheduled emails."],
 attendance:["Daily Attendance shows present, absent, late and currently working employees.","Monthly Summary shows present days, half days, late days and total hours for the selected month.","Payslips generates, edits, previews, prints and emails INR payroll documents.","Payroll supports encrypted PAN, UAN, PF, ESI, banking, IFSC, leave balances, deductions and CTC details.","Employee Public Form emails a seven-day single-use onboarding URL and can copy the URL.","Leave Approvals, Add Employee Leave, Holidays and authorized WFH access complete the attendance workflow."],
 employees:["Review employee identity, employee ID and company-login assignment.","See profile, attendance and performance information where permitted.","Public onboarding creates the next sequential EMP-I employee ID.","Admin can assign position, schedule and company login after onboarding."],
 profile:["Overview shows your employee information.","Performance shows activity available for your role.","Attendance shows your personal time and attendance information.","Company Identity shows the account and employee relationship."],
 users:["Create and maintain company login accounts.","Assign positions, account status and employee relationships.","Permissions are managed separately through the Permission Matrix."],
 permissions:["Position mode defines default permissions for a role.","User mode adds employee-specific overrides.","Permissions cover view, create, edit, delete, import, export, approve, share and other supported actions.","Data scope determines whether a user sees their own records or all authorized records.","Super Admin access remains protected."],
 chat:["Direct messages support one-to-one communication.","Groups and Teams support multi-user collaboration.","Resource Discussions keep messages connected to a page or record.","Unread counters, attachments, replies and notifications help users follow activity."],
 chat_notifications:["Shows unread messages, mentions, replies and discussion events.","Select an item to open its related conversation.","Mark all as read clears the current unread state."],
 chat_admin:["Review conversations, participants and resource contexts.","Audit chat activity using Admin-authorized access.","Regular messaging remains in Enterprise Chat."],
 training:["Review and manage training information available to your role.","Use employee and candidate records for related people information."],
 candidate_onboarding:["Collect and manage information required for candidate onboarding.","Use Candidates to review the completed profile and documents.","W2 Forms provides a separate secure tax-information workflow."],
 vendor_onboarding:["Collect new vendor details through the onboarding workflow.","Completed organizations are managed from Prime Vendors."],
 w2_forms:["Review secure W2 submissions and their processing status.","Sensitive tax information remains within its protected workflow.","Access and actions follow W2 resource permissions."],
 positions:["Maintain organization positions used by users and employees.","Positions supply defaults to the Permission Matrix."],
 resources:["The resource catalog is the centralized list of application modules.","A resource defines its display name, route, component and availability.","Permissions reference resources to control pages and actions."]
};const greeting=/^(hi|hai|hello|hey|good\s*(morning|afternoon|evening))\b/i;
export default function ApplicationAssistant(){
 const location=useLocation(),navigate=useNavigate(),{resources}=usePermissions(),[open,setOpen]=useState(false),[text,setText]=useState(""),[typing,setTyping]=useState(false),[messages,setMessages]=useState([{role:"assistant",text:"Welcome! Select any available module to see everything it contains and open the right page or action.",options:["dashboard"]}]),end=useRef(null);
 const available=useMemo(()=>{const allowed=new Set(resources.filter(r=>r.permissions?.view).map(r=>r.resource));allowed.add("dashboard");return Object.keys(catalog).filter(id=>allowed.has(id)||resources.some(r=>r.permissions?.view&&r.route===catalog[id]?.actions?.[0]?.[1]))},[resources]);
 const current=useMemo(()=>available.find(id=>catalog[id].actions.some(([,route])=>route.split(/[?#]/)[0]===location.pathname)),[available,location.pathname]);
 useEffect(()=>{end.current?.scrollIntoView({behavior:"smooth"})},[messages,typing,open]);
 const deliver=message=>{setTyping(true);window.setTimeout(()=>{setMessages(v=>[...v,message]);setTyping(false)},260)};
 const menu=()=>deliver({role:"assistant",text:"All resources available to your account:",options:available});
 const explain=id=>{const topic=catalog[id];if(!topic)return;deliver({role:"assistant",text:topic.summary,details:details[id]||[],topic:id,actions:topic.actions,options:topic.related.filter(x=>available.includes(x))})};
 const go=destination=>{if(destination.startsWith("search:")){const term=destination.slice(7);setOpen(false);window.setTimeout(()=>{const input=document.querySelector(".e2e_navbar_search");if(!input)return;const setter=Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype,"value")?.set;setter?.call(input,term);input.dispatchEvent(new Event("input",{bubbles:true}));input.focus()},0);return}navigate(destination);setOpen(false)};
 const choose=id=>{setMessages(v=>[...v,{role:"user",text:catalog[id]?.label||id}]);explain(id)};
 const send=e=>{e.preventDefault();const q=text.trim();if(!q)return;setMessages(v=>[...v,{role:"user",text:q}]);setText("");if(greeting.test(q)){deliver({role:"assistant",text:"Hello! Choose a module, ask what a page contains, or type “search” followed by a name.",options:available});return}const search=q.match(/^search\s+(.+)/i);if(search){go("search:"+search[1]);return}const lower=q.toLowerCase(),id=available.find(key=>catalog[key].keys.some(k=>lower.includes(k)));if(id)explain(id);else deliver({role:"assistant",text:"I could not match that to one module. Select an available area below and I’ll show its details and working actions.",options:available})};
 return <aside className={`app-assistant ${open?"open":""}`}><button className="app-assistant-launch" onClick={()=>setOpen(v=>!v)} aria-label={open?"Close application assistant":"Open application assistant"}><FaRobot/></button>{open&&<section role="dialog" aria-label="E2E application assistant"><header><span><FaRobot/></span><div><strong>E2E Assistant</strong><small>{current?`Currently viewing ${catalog[current].label}`:"Centralized application guide"}</small></div><button onClick={()=>setOpen(false)} aria-label="Close"><FaTimes/></button></header><div className="app-assistant-messages">{messages.map((m,i)=><article key={i} className={m.role}><p>{m.text}</p>{m.details?.length>0&&<ul className="app-assistant-details">{m.details.map((detail,index)=><li key={index}>{detail}</li>)}</ul>}{m.actions&&<div className="app-assistant-actions">{m.actions.map(([label,route])=><button key={route+label} onClick={()=>go(route)}><FaExternalLinkAlt/>{label}</button>)}</div>}{m.options?.length>0&&<div className="app-assistant-options">{m.options.map(id=><button key={id} onClick={()=>choose(id)}>{catalog[id]?.label||id}</button>)}</div>}{m.role==="assistant"&&<button className="app-assistant-menu" onClick={menu}><FaThLarge/> All options</button>}</article>)}{typing&&<article className="assistant assistant-typing"><i/><i/><i/></article>}<div ref={end}/></div><div className="app-assistant-suggestions">{current&&<button onClick={()=>choose(current)}>This page</button>}<button onClick={()=>choose("dashboard")}>Dashboard</button><button onClick={menu}><FaArrowLeft/> All options</button><button onClick={()=>setText("search ")}><FaSearch/> Search</button></div><form onSubmit={send}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Ask about a page or search a record" aria-label="Ask the application assistant"/><button disabled={!text.trim()||typing} aria-label="Send question"><FaPaperPlane/></button></form><footer><FaComments/> Permission-aware application help and navigation.</footer></section>}</aside>;
}