import {useCallback,useEffect,useMemo,useState} from "react";
import "../../styles/Dashboard/sidebar.css";
import {NavLink,useLocation} from "react-router-dom";
import {FaChevronDown,FaSearch,FaShieldAlt,FaTimes} from "react-icons/fa";
import {sidebarConfig} from "./SidebarConfig";
import {usePermissions} from "../../auth/PermissionContext";
import {getConversations,getNotificationCenter} from "../../api/chatApi";
import {RESOURCE_GROUPS,groupResources} from "./ResourceGroups";
const STORE="e2e-sidebar-open-groups",count=n=>n>99?"99+":n;
const initialOpen=()=>{try{const value=JSON.parse(localStorage.getItem(STORE));if(Array.isArray(value))return value}catch(e){}return RESOURCE_GROUPS.map(group=>group.id)};
export default function Sidebar(){
 const{resources}=usePermissions(),location=useLocation(),[unread,setUnread]=useState({chat:0,notifications:0}),[open,setOpen]=useState(initialOpen),[query,setQuery]=useState("");
 const visible=useMemo(()=>resources.filter(item=>item.permissions?.view&&item.route&&item.resource_type==="PAGE"&&item.component_key),[resources]);
 const groups=useMemo(()=>{const term=query.trim().toLowerCase();return groupResources(visible).map(group=>term?{...group,items:group.items.filter(item=>`${item.display_name} ${item.resource}`.toLowerCase().includes(term))}:group).filter(group=>group.items.length)},[visible,query]);
 const refresh=useCallback(async()=>{try{const[chats,alerts]=await Promise.all([getConversations(),getNotificationCenter()]);setUnread({chat:chats.reduce((sum,item)=>sum+Number(item.unread_count||0),0),notifications:Number(alerts.unread||0)})}catch(e){}},[]);
 useEffect(()=>{refresh();const timer=setInterval(()=>document.visibilityState==="visible"&&refresh(),15000),watch=()=>document.visibilityState==="visible"&&refresh();document.addEventListener("visibilitychange",watch);return()=>{clearInterval(timer);document.removeEventListener("visibilitychange",watch)}},[refresh]);
 useEffect(()=>{const active=groups.find(group=>group.items.some(item=>item.route==="/dashboard"?location.pathname===item.route:location.pathname.startsWith(item.route)));if(active)setOpen(current=>current.includes(active.id)?current:[...current,active.id])},[groups,location.pathname]);
 useEffect(()=>localStorage.setItem(STORE,JSON.stringify(open)),[open]);
 const toggle=id=>setOpen(current=>current.includes(id)?current.filter(value=>value!==id):[...current,id]),badge=item=>item.resource==="chat"?unread.chat:item.resource==="chat_notifications"?unread.notifications:0;
 return <aside className="e2e_sidebar_container"><div className="e2e_sidebar_logo_section"><img src="/logo.png" alt="E2E Tracking Services" className="e2e_sidebar_logo"/><div><h2>E2E TRACKING</h2><p>SERVICES</p></div></div><div className="e2e_sidebar_divider"/><nav className="e2e_sidebar_resource_scroll" aria-label="Dashboard resources"><label className="e2e_sidebar_search"><FaSearch/><span className="e2e_sr_only">Find a resource</span><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a resource..."/>{query&&<button type="button" onClick={()=>setQuery("")} aria-label="Clear resource search"><FaTimes/></button>}</label><div className="e2e_sidebar_groups">{groups.map((group,index)=>{const expanded=Boolean(query.trim())||open.includes(group.id),Icon=group.icon,panel=`sidebar-${group.id}`;return <section className={`e2e_sidebar_group ${expanded?"is-open":""}`} key={group.id} style={{"--group-index":index}}><div className="e2e_sidebar_group_header"><NavLink to={group.items[0].route} className="e2e_sidebar_group_link"><Icon/><b>{group.label}</b></NavLink><button type="button" className="e2e_sidebar_group_toggle" onClick={()=>toggle(group.id)} aria-label={`${expanded?"Collapse":"Expand"} ${group.label}`} aria-expanded={expanded} aria-controls={panel}><FaChevronDown/></button></div><div className="e2e_sidebar_group_reveal" id={panel}><div className="e2e_sidebar_menu">{group.items.map((item,itemIndex)=>{const itemBadge=badge(item);return <NavLink key={item.id} to={item.route} end={item.route==="/dashboard"} className={({isActive})=>`e2e_sidebar_menu_item ${isActive?"e2e_sidebar_active":""}`} style={{"--item-index":itemIndex}} title={item.display_name}>{sidebarConfig[item.resource]?.icon||<FaShieldAlt className="menuIcon"/>}<span>{item.display_name}</span>{itemBadge>0&&<b className="e2e_sidebar_unread" aria-label={`${itemBadge} unread`}>{count(itemBadge)}</b>}</NavLink>})}</div></div></section>})}{!groups.length&&<div className="e2e_sidebar_empty"><FaSearch/><strong>No resources found</strong><span>Try a different search.</span></div>}</div></nav></aside>
}