import {useCallback,useEffect,useState} from "react";
import {useNavigate} from "react-router-dom";
import {FaCog,FaEnvelope,FaShieldAlt,FaCheckCircle} from "react-icons/fa";
import {getMailSender,saveMailSender,removeMailSender,getLeaveMailSettings,saveLeaveMailSettings} from "../api/employeeApi";
import {usePermissions} from "../auth/PermissionContext";
import ConfirmDialog from "./ConfirmDialog";
import "../styles/attendanceConfigurations.css";
const defaults={email:"",host:"smtp.ionos.com",port:587,encryption:"tls",from_name:"BeeData Technologies",password:"",to_email:""};
function MailboxCard({organization=false}){
 const {user}=usePermissions();
 const [status,setStatus]=useState(null),[form,setForm]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[disconnect,setDisconnect]=useState(false);
 const fetchStatus=useCallback(()=>{setLoading(true);setError("");return (organization?getLeaveMailSettings():getMailSender()).then(setStatus).catch(e=>setError(e?.response?.data?.message||"Mailbox settings could not be loaded.")).finally(()=>setLoading(false))},[organization]);
 useEffect(()=>{fetchStatus()},[fetchStatus]);
 const edit=()=>{const data=status?.data||{};setError("");setMessage("");setForm({...defaults,email:data.smtp_username||data.from_email||user?.email||"",host:data.smtp_host||defaults.host,port:data.smtp_port||587,encryption:data.encryption||"tls",from_name:data.from_name||defaults.from_name,to_email:data.to_email||""})};
 const save=async event=>{event.preventDefault();if(busy)return;setBusy(true);setError("");setMessage("");try{const result=await(organization?saveLeaveMailSettings({...form,from_email:form.email}):saveMailSender(form));if(!result.success)throw new Error(result.message||"Mailbox could not be saved.");setStatus(result);setForm(null);setMessage(result.message||"Mailbox verified and saved.")}catch(e){setError(e?.response?.data?.message||e.message||"Mailbox authentication failed.")}finally{setBusy(false)}};
 const remove=async()=>{setDisconnect(false);setBusy(true);setError("");try{await removeMailSender();setStatus({configured:false});setForm(null);setMessage("Sender mailbox disconnected.")}catch(e){setError(e?.response?.data?.message||"Mailbox could not be disconnected.")}finally{setBusy(false)}};
 const change=key=>event=>setForm(current=>({...current,[key]:event.target.value}));
 return <article className="attendance-mail-card" aria-label={organization?"Leave Approval Mailbox":"Your Sender Mailbox"}><header className="attendance-config-heading"><span className="attendance-config-icon"><FaEnvelope/></span><div><h2>{organization?"Leave Approval Mailbox":"Your Sender Mailbox"}</h2><p>{organization?"Organization-wide sender and HR recipient for automatic leave approval requests.":"One authenticated mailbox for candidate pre-offers, employee public forms, and payslip emails."}</p></div></header>
 {loading?<p role="status">Loading mailbox settings...</p>:<><div className="attendance-mail-summary"><span className={`attendance-mail-status ${status?.configured?"ready":""}`}><FaCheckCircle/> {status?.configured?"Verified":"Not configured"}</span>{status?.configured&&<><strong>{status.data.smtp_username||status.data.from_email}</strong><small>{status.data.smtp_host}:{status.data.smtp_port} | {String(status.data.encryption||"tls").toUpperCase()}</small>{organization&&<small>HR recipient: {status.data.to_email}</small>}</>}</div>
 {!form&&<div className="attendance-config-actions"><button type="button" className="primary" onClick={status?edit:fetchStatus} disabled={busy}>{status?(status.configured?"Update Mailbox":"Configure Mailbox"):"Retry Loading"}</button>{!organization&&status?.configured&&<button type="button" className="danger" disabled={busy} onClick={()=>setDisconnect(true)}>Disconnect</button>}</div>}
 {form&&<form className="attendance-mail-form" onSubmit={save}><fieldset disabled={busy}><label>Sender Email<input required type="email" value={form.email} onChange={change("email")}/><small>Enter any mailbox you can authenticate with its SMTP credentials.</small></label><label>Sender Name<input required maxLength={190} value={form.from_name} onChange={change("from_name")}/></label><label>SMTP Host<input required maxLength={190} value={form.host} onChange={change("host")}/></label><label>SMTP Port<input required type="number" min="1" max="65535" value={form.port} onChange={change("port")}/></label><label>Security<select value={form.encryption} onChange={change("encryption")}><option value="tls">TLS / STARTTLS</option><option value="ssl">SSL</option><option value="none">None</option></select></label>{organization&&<label>HR Approval Recipient<input required type="email" value={form.to_email} onChange={change("to_email")}/></label>}<label>Webmail / App Password<input required={!organization||!status?.configured} type="password" autoComplete="new-password" value={form.password} onChange={change("password")} placeholder={organization&&status?.configured?"Leave blank to retain the saved password":"Enter mailbox password"}/></label></fieldset><p className="attendance-mail-security"><FaShieldAlt/> Saving sends a verification email to the sender. Credentials are encrypted and passwords are never displayed.</p><div className="attendance-config-actions"><button disabled={busy} className="primary">{busy?"Verifying...":"Verify & Save"}</button><button type="button" disabled={busy} onClick={()=>{setForm(null);setError("")}}>Cancel</button></div></form>}</>}
 {error&&<p className="collection-error" role="alert">{error}</p>}{message&&<p className="attendance-config-success" role="status">{message}</p>}<ConfirmDialog open={disconnect} title="Disconnect sender mailbox?" message="Candidate invitations and payslip emails will require mailbox setup again." confirmLabel="Disconnect" danger onCancel={()=>setDisconnect(false)} onConfirm={remove}/></article>;
}
export default function AttendanceConfigurations(){
 const {can,user}=usePermissions();const navigate=useNavigate();
 const senderAccess=can("employees","create")||can("payslips","share");
 const organizationAccess=can("attendance","edit")&&(user?.super_admin||Number(user?.position_id)===1);
 return <section className="attendance-configurations"><header className="attendance-config-heading"><span className="attendance-config-icon"><FaCog/></span><div><p className="attendance-config-eyebrow">ATTENDANCE MANAGEMENT</p><h1>Configurations</h1><p>Manage email delivery for onboarding, payroll, and leave approvals in one place.</p></div></header><div className="attendance-config-grid">{senderAccess&&<MailboxCard/>}{organizationAccess&&<MailboxCard organization/>}</div>{!senderAccess&&!organizationAccess&&<p>Your account does not have permission to configure mailboxes.</p>}<div className="attendance-config-actions">{can("employees","view")&&<button type="button" onClick={()=>navigate("/dashboard/employee-status")}>Go to Employees</button>}{can("payslips","view")&&<button type="button" onClick={()=>navigate("/dashboard/attendance?assistant=payslips")}>Go to Payslips</button>}</div></section>;
}
