import {render,screen,fireEvent,waitFor} from "@testing-library/react";
import AttendanceActions from "./AttendanceActions";
import {getHolidays,getLeaves,getTodayAttendance,submitLeave,saveHoliday} from "../api/employeeApi";
jest.mock("../api/employeeApi",()=>({getHolidays:jest.fn(),getLeaves:jest.fn(),getTodayAttendance:jest.fn(),submitLeave:jest.fn(),reviewLeave:jest.fn(),clockAttendance:jest.fn(),deleteHoliday:jest.fn(),saveHoliday:jest.fn()}));
beforeEach(()=>{getHolidays.mockResolvedValue({data:[]});getLeaves.mockResolvedValue({data:[]});getTodayAttendance.mockResolvedValue({record:null});});
test("profile leave view loads leave controls without clock or holidays",async()=>{const changed=jest.fn();submitLeave.mockResolvedValue({message:"Leave submitted"});render(<AttendanceActions isOwn canManage showClock={false} showHolidays={false} leaveTitle="Leave Management" onChanged={changed}/>);await waitFor(()=>expect(getLeaves).toHaveBeenCalled());expect(getHolidays).not.toHaveBeenCalled();expect(getTodayAttendance).not.toHaveBeenCalled();expect(screen.getByRole("heading",{name:"Leave Management"})).toBeInTheDocument();expect(screen.queryByText("Company Holidays")).not.toBeInTheDocument();const dates=document.querySelectorAll('.leave-form input[type=date]');fireEvent.change(dates[0],{target:{value:"2026-10-07"}});fireEvent.change(dates[1],{target:{value:"2026-10-08"}});fireEvent.change(screen.getByPlaceholderText("Reason"),{target:{value:"Family appointment"}});fireEvent.submit(document.querySelector('.leave-form'));await waitFor(()=>expect(changed).toHaveBeenCalled());expect(submitLeave).toHaveBeenCalledWith(expect.objectContaining({start_date:"2026-10-07",end_date:"2026-10-08",reason:"Family appointment"}));});
test("attendance page retains leave and holiday controls by default",async()=>{render(<AttendanceActions canManage/>);await waitFor(()=>expect(getLeaves).toHaveBeenCalled());expect(getHolidays).toHaveBeenCalled();expect(screen.getByText("Company Holidays")).toBeInTheDocument();expect(screen.getByText("Leave Management")).toBeInTheDocument();});
test("attendance-only view does not fetch or show leave",async()=>{render(<AttendanceActions canManage showLeave={false}/>);await waitFor(()=>expect(getHolidays).toHaveBeenCalled());expect(getLeaves).not.toHaveBeenCalled();expect(screen.queryByText("Leave Management")).not.toBeInTheDocument();});

test("compact holiday saving refreshes attendance and does not fetch leave or clock status",async()=>{const changed=jest.fn();saveHoliday.mockResolvedValue({message:"Holiday saved"});render(<AttendanceActions canManage compactHolidays holidayYear={2026} showLeave={false} showClock={false} onChanged={changed}/>);await waitFor(()=>expect(getHolidays).toHaveBeenCalledWith(2026));fireEvent.change(screen.getByLabelText("Company holiday date"),{target:{value:"2026-10-20"}});fireEvent.change(screen.getByLabelText("Company holiday name"),{target:{value:"Office holiday"}});fireEvent.click(screen.getByRole("button",{name:"Save Holiday"}));await waitFor(()=>expect(changed).toHaveBeenCalledTimes(1));expect(saveHoliday).toHaveBeenCalledWith(expect.objectContaining({holiday_date:"2026-10-20",name:"Office holiday"}));expect(screen.getByLabelText("Company holiday name")).toHaveValue("");});
