import {useState} from "react";
import {useNavigate} from "react-router-dom";
import {FaCalendarCheck,FaClock,FaUserCheck,FaUserTimes,FaUsers,FaChartBar,FaEye,FaPen,FaSignOutAlt} from "react-icons/fa";
import EmployeeRowActions from "./EmployeeRowActions";
import ConfirmDialog from "./ConfirmDialog";
import {editAttendance,adminLogoutAttendance} from "../api/employeeApi";
const num=value=>Number(value)||0;
export function attendanceDashboardMetrics(today){const rows=today.data||[],present=rows.filter(r=>r.present).length,late=rows.filter(r=>r.present&&Number(r.status)===0).length,working=rows.filter(r=>r.present&&r.time_out==="00:00:00").length;return {total:rows.length,present,late,working,absent:rows.length-present,hours:rows.reduce((n,r)=>n+num(r.hours),0),completed:present-working};}
function Donut({title,values,total,label}){let start=0;const colors=["#13c79a","#087bff","#f5a524","#ef526b"];const stops=values.map((v,i)=>{const from=start;start+=total?num(v[1])/total*100:0;return `${colors[i]} ${from}% ${start}%`});return <article className="daily-chart-card"><h3><FaChartBar/>{title}</h3><div className="daily-donut-body"><div className="daily-donut" style={{background:total?`conic-gradient(${stops.join(",")})`:"#e5eaf3"}}><span><strong>{total}</strong><small>{label}</small></span></div><ul>{values.map(([name,value],i)=><li key={name}><i style={{background:colors[i]}}/><span>{name}</span><b>{value}</b><small>{total?Math.round(value/total*100):0}%</small></li>)}</ul></div></article>}
export default function DailyAttendanceDashboard({today,selectedDate,onDateChange,localDate,onRefresh,canManage,canExport}){
 const navigate=useNavigate(),[page,setPage]=useState(1),[size,setSize]=useState(10),[editing,setEditing]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const rows=today.data||[],m=attendanceDashboardMetrics(today),pages=Math.max(1,Math.ceil(rows.length/size)),current=Math.min(page,pages),visible=rows.slice((current-1)*size,current*size),maxHours=Math.max(9,...rows.map(r=>num(r.hours)));
 const [logout,setLogout]=useState(null);
 const confirmLogout=async()=>{if(busy)return;setBusy(true);setError("");try{const result=await adminLogoutAttendance(logout.row.attendance_id,{day_type:logout.day_type});if(result.success===false)throw Error(result.message);setLogout(null);window.dispatchEvent(new Event("e2e-attendance-changed"));await onRefresh();}catch(e){setError(e?.response?.data?.message||e.message||"Logout could not be saved.");}finally{setBusy(false)}};
 const close=()=>{if(!busy)setEditing(null)};
 const save=async()=>{if(busy)return;if(!editing.time_in||!editing.time_out||editing.time_out<=editing.time_in){setError("Time out must be after time in (Eastern Time).");return;}if(!editing.notes.trim()){setError("Enter a correction reason.");return;}setBusy(true);setError("");try{const result=await editAttendance(editing.row.attendance_id,{time_in:editing.time_in,time_out:editing.time_out,notes:editing.notes});if(result.success===false)throw Error(result.message);setEditing(null);await onRefresh();}catch(e){setError(e?.response?.data?.message||e.message||"Attendance could not be updated.");}finally{setBusy(false)}};
 return <section className="attendance-admin-section daily-attendance-dashboard"><div className="attendance-section-title"><div><h2><FaCalendarCheck/>Daily Attendance</h2><p>Today's active employees, attendance and shift status. All times in ET.</p></div><div className="daily-date-controls"><label className="attendance-date-filter">Date<input aria-label="Attendance date" type="date" max={localDate} value={selectedDate} onChange={e=>{setPage(1);onDateChange(e.target.value)}}/></label><button type="button" onClick={()=>{setPage(1);onDateChange(localDate)}}>Today</button>{canExport&&<button type="button" className="daily-export" onClick={()=>{const csv=[['Employee','Employee ID','Role','Time In (ET)','Time Out (ET)','Hours','Status'],...rows.map(r=>[r.legal_name,r.employee_id,r.role,r.present?r.time_in:'',r.present?r.time_out:'',r.hours,r.present?'Present':'Absent'])].map(row=>row.map(v=>'"'+String(v??'').replace(/"/g,'""').replace(/^[=+@-]/,"'$&")+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'})),link=document.createElement('a');link.href=url;link.download=`attendance-${selectedDate}.csv`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}>Export</button>}</div></div>
 <div className="attendance-today-cards">{[["Active Employees",m.total,FaUsers,"present"],["Logged In",m.present,FaUserCheck,"present"],["Late Logins",m.late,FaClock,"late"],["On Break",null,FaUserTimes,"absent"],["Total Working Hours",`${m.hours.toFixed(1)} h`,FaClock,"hours"]].map(([label,value,Icon,color])=><article key={label} className={color}><Icon/><span><small>{label}</small><strong>{value??"--"}</strong></span><em>{value===null?"Not tracked":m.total&&typeof value==='number'?`${Math.round(value/m.total*100)}%`:"Recorded hours"}</em></article>)}</div>
 <div className="daily-roster-heading"><h3><FaUsers/>{selectedDate===localDate?"Today's Attendance":"Attendance"} <small>(Active Employees Only)</small></h3><label>Rows<select aria-label="Daily attendance rows" value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1)}}>{[10,25,50,100].map(n=><option key={n}>{n}</option>)}</select></label></div>
 <div className="attendance-admin-table"><table><thead><tr>{['Employee','Employee ID','Role','Shift Time (ET)','Login Time','Logout Time','Work Hours','Status','Actions'].map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{visible.map(row=><tr key={row.id}><td><span className="daily-employee-name"><i>{(row.legal_name||'E').split(/\s+/).slice(0,2).map(v=>v[0]).join('')}</i><strong>{row.legal_name}</strong></span></td><td>{row.employee_id||'Not assigned'}</td><td>{row.role||'Not assigned'}</td><td>{row.shift_start&&row.shift_end?`${row.shift_start.slice(0,5)} - ${row.shift_end.slice(0,5)}`:'Not configured'}</td><td>{row.present?row.time_in:'--'}</td><td>{row.present?(row.time_out==='00:00:00'?'Working':row.time_out):'--'}</td><td>{row.present?`${num(row.hours).toFixed(2)} h`:'--'}</td><td><mark className={!row.present?'rejected':row.time_out==='00:00:00'?'working':'approved'}>{!row.present?'Absent':row.time_out==='00:00:00'?'Working':'Present'}</mark>{row.present&&Number(row.status)===0&&<small className="daily-late-label">Late</small>}</td><td><EmployeeRowActions employee={row} actions={[["View",FaEye,()=>navigate(`/dashboard/employee-status/${row.id}`)],...(canManage&&row.attendance_id?[["Edit",FaPen,()=>{setError('');setEditing({row,time_in:row.time_in?.slice(0,5)||'',time_out:row.time_out==='00:00:00'?'':row.time_out?.slice(0,5)||'',notes:''})}]]:[]),...(canManage?[["Logout",FaSignOutAlt,()=>{setError('');setLogout({row,day_type:'full_day'})},!row.attendance_id||row.time_out!=='00:00:00',!row.attendance_id?'Employee has not logged in for this date':row.time_out!=='00:00:00'?'Employee has already logged out':'Log out this employee']]:[])]}/></td></tr>)}{!visible.length&&<tr><td colSpan="9" className="daily-empty">No active employee attendance records for this date.</td></tr>}</tbody></table></div>
 <footer className="daily-pagination"><span>{rows.length?`${(current-1)*size+1}-${Math.min(current*size,rows.length)} of ${rows.length} employees`:'0 employees'}</span><div><button disabled={current<=1} onClick={()=>setPage(current-1)}>Previous</button><strong>{current} / {pages}</strong><button disabled={current>=pages} onClick={()=>setPage(current+1)}>Next</button></div></footer>
 <div className="daily-charts"><Donut title="Attendance Overview" total={m.total} label="Employees" values={[["On Time",m.present-m.late],["Late",m.late],["Absent",m.absent]]}/><article className="daily-chart-card"><h3><FaChartBar/>Recorded Working Hours</h3><div className="daily-hours-bars">{rows.slice(0,8).map(row=><div key={row.id} title={`${row.legal_name}: ${num(row.hours).toFixed(2)} hours`}><span>{num(row.hours).toFixed(1)}</span><i style={{height:`${num(row.hours)/maxHours*95}px`}}/><small>{row.legal_name?.split(' ')[0]}</small></div>)}{!rows.length&&<p>No records for this date.</p>}</div><p className="daily-chart-note">First {Math.min(8,rows.length)} employees &bull; recorded hours</p></article><Donut title="Shift Status" total={m.total} label="Employees" values={[["Completed",m.completed],["In Progress",m.working],["Not Started",m.absent]]}/></div>
 <ConfirmDialog open={Boolean(logout)} title="Confirm Employee Logout" message={`${logout?.row.legal_name||''} - ${selectedDate}. Login: ${logout?.row.time_in||''} ET.`} danger={false} busy={busy} confirmLabel="Confirm Logout" onCancel={()=>{if(!busy)setLogout(null)}} onConfirm={confirmLogout}>{logout&&<div className="daily-logout-choice"><label>Attendance Day<select disabled={busy} value={logout.day_type} onChange={e=>setLogout({...logout,day_type:e.target.value})}><option value="full_day">Full Day</option><option value="half_day">Half Day</option></select></label>{error&&<p role="alert">{error}</p>}</div>}</ConfirmDialog>
 <ConfirmDialog open={Boolean(editing)} title="Edit Attendance" message={`${editing?.row.legal_name||''} - ${selectedDate} (Eastern Time). Hours and punctuality are recalculated.`} danger={false} busy={busy} confirmLabel="Save Correction" onCancel={close} onConfirm={save}>{editing&&<div className="daily-edit-fields"><label>Time In (ET)<input disabled={busy} type="time" value={editing.time_in} onChange={e=>setEditing({...editing,time_in:e.target.value})}/></label><label>Time Out (ET)<input disabled={busy} type="time" value={editing.time_out} onChange={e=>setEditing({...editing,time_out:e.target.value})}/></label><label>Correction Reason<textarea disabled={busy} value={editing.notes} onChange={e=>setEditing({...editing,notes:e.target.value})}/></label>{error&&<p role="alert">{error}</p>}</div>}</ConfirmDialog></section>;
}
