import {fireEvent,render,screen,waitFor} from "@testing-library/react";
import DailyAttendanceDashboard,{attendanceDashboardMetrics} from "./DailyAttendanceDashboard";
import {editAttendance,adminLogoutAttendance} from "../api/employeeApi";
const mockNavigate=jest.fn();jest.mock("react-router-dom",()=>({useNavigate:()=>mockNavigate}),{virtual:true});jest.mock("../api/employeeApi",()=>({editAttendance:jest.fn(),adminLogoutAttendance:jest.fn()}));
const rows=[{id:1,attendance_id:10,legal_name:'Test Employee',employee_id:'BDT-I-132',present:true,status:1,time_in:'09:55:00',time_out:'18:30:00',hours:8.58},{id:2,attendance_id:11,legal_name:'Late Employee',present:true,status:0,time_in:'10:11:00',time_out:'00:00:00',hours:0},{id:3,legal_name:'Absent Employee',present:false,hours:0}];
const props={today:{data:rows},selectedDate:'2026-10-07',localDate:'2026-10-07',onDateChange:jest.fn(),onRefresh:jest.fn(),canManage:true};
beforeEach(()=>jest.clearAllMocks());
test('metrics use recorded data and distinguish lateness from presence',()=>{expect(attendanceDashboardMetrics(props.today)).toEqual({total:3,present:2,late:1,working:1,absent:1,hours:8.58,completed:1});render(<DailyAttendanceDashboard {...props}/>);expect(screen.getByText('Not tracked')).toBeInTheDocument();expect(document.querySelector('.daily-late-label')).toHaveTextContent('Late');});
test('editing validates times, preserves errors and retries successfully',async()=>{editAttendance.mockRejectedValueOnce({response:{data:{message:'Try again'}}}).mockResolvedValueOnce({success:true});render(<DailyAttendanceDashboard {...props}/>);fireEvent.click(screen.getByRole('button',{name:'Actions for Test Employee'}));fireEvent.click(screen.getByRole('menuitem',{name:'Edit'}));fireEvent.change(screen.getByLabelText('Time Out (ET)'),{target:{value:'09:00'}});fireEvent.click(screen.getByRole('button',{name:'Save Correction'}));expect(await screen.findByRole('alert')).toHaveTextContent('Time out must be after time in');expect(editAttendance).not.toHaveBeenCalled();fireEvent.change(screen.getByLabelText('Time Out (ET)'),{target:{value:'18:30'}});fireEvent.change(screen.getByLabelText('Correction Reason'),{target:{value:'Verified clock correction'}});fireEvent.click(screen.getByRole('button',{name:'Save Correction'}));expect(await screen.findByRole('alert')).toHaveTextContent('Try again');fireEvent.click(screen.getByRole('button',{name:'Save Correction'}));await waitFor(()=>expect(props.onRefresh).toHaveBeenCalledTimes(1));expect(editAttendance).toHaveBeenLastCalledWith(10,{time_in:'09:55',time_out:'18:30',notes:'Verified clock correction'});expect(screen.queryByRole('alertdialog')).toBeNull();});
test('absent rows offer view without an invalid correction action',()=>{render(<DailyAttendanceDashboard {...props}/>);fireEvent.click(screen.getByRole('button',{name:'Actions for Absent Employee'}));expect(screen.queryByRole('menuitem',{name:'Edit'})).toBeNull();expect(screen.getByRole('menuitem',{name:'Logout'})).toBeDisabled();expect(screen.getByRole('menuitem',{name:'Logout'})).toHaveAttribute('title','Employee has not logged in for this date');fireEvent.click(screen.getByRole('menuitem',{name:'View'}));expect(mockNavigate).toHaveBeenCalledWith('/dashboard/employee-status/3');expect(screen.queryByRole('button',{name:'Export'})).toBeNull();});

test('admin logout offers only a day selector and retries failed confirmation',async()=>{adminLogoutAttendance.mockRejectedValueOnce({response:{data:{message:'Already logged out'}}}).mockResolvedValueOnce({success:true});render(<DailyAttendanceDashboard {...props}/>);fireEvent.click(screen.getByRole('button',{name:'Actions for Late Employee'}));fireEvent.click(screen.getByRole('menuitem',{name:'Logout'}));expect(screen.queryByLabelText('Logout Time (ET)')).toBeNull();expect(screen.queryByLabelText('Logout Reason')).toBeNull();fireEvent.change(screen.getByLabelText('Attendance Day'),{target:{value:'half_day'}});fireEvent.click(screen.getByRole('button',{name:'Confirm Logout'}));expect(await screen.findByRole('alert')).toHaveTextContent('Already logged out');fireEvent.click(screen.getByRole('button',{name:'Confirm Logout'}));await waitFor(()=>expect(screen.queryByRole('alertdialog')).toBeNull());expect(adminLogoutAttendance).toHaveBeenLastCalledWith(11,{day_type:'half_day'});});
test('completed shifts never offer logout and read-only viewers cannot logout',()=>{const {unmount}=render(<DailyAttendanceDashboard {...props}/>);fireEvent.click(screen.getByRole('button',{name:'Actions for Test Employee'}));expect(screen.getByRole('menuitem',{name:'Logout'})).toBeDisabled();unmount();render(<DailyAttendanceDashboard {...props} canManage={false}/>);fireEvent.click(screen.getByRole('button',{name:'Actions for Late Employee'}));expect(screen.queryByRole('menuitem',{name:'Logout'})).toBeNull();});
