import {createContext,useContext,useState} from "react";
import {FaUser,FaUsers,FaGraduationCap,FaBriefcase,FaCertificate,FaFileAlt,FaDownload,FaCheckCircle,FaChartPie,FaEnvelope,FaPhone,FaCalendarAlt,FaMapMarkerAlt,FaIdBadge} from "react-icons/fa";
import EmployeeFormModal from "./EmployeeFormModal";
import {downloadEmployeeDocument} from "../api/employeeApi";
import {normalizeCollection} from "../utils/employeeCollection";
import {employeeProfileCompletion} from "../utils/employeeProfileCompletion";
import "../styles/employeeProfile.css";
const detailIcon=label=>/mail/i.test(label)?FaEnvelope:/phone/i.test(label)?FaPhone:/date|year/i.test(label)?FaCalendarAlt:/address|location/i.test(label)?FaMapMarkerAlt:/employee id/i.test(label)?FaIdBadge:/position|department|employment/i.test(label)?FaBriefcase:FaUser;
const displayValue=(label,value)=>{if(!value||!/Date of Birth|Joining Date/.test(label))return value;const date=new Date(String(value).slice(0,10)+"T00:00:00");return Number.isFinite(date.getTime())?date.toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"}):value};
const Details=({rows})=><dl className="profile-information-grid">{rows.map(([label,value])=>{const Icon=detailIcon(label);return <div key={label}><dt><Icon aria-hidden="true"/>{label}</dt><dd className={!value?"missing":""}>{displayValue(label,value)||"Not provided"}</dd></div>})}</dl>;
const SectionContext=createContext(null);
const sectionKeys={"profile-details":"personal","profile-family":"family","profile-bank":"bank","profile-education":"education","profile-experience":"experience","profile-certifications":"certifications","profile-references":"references","profile-documents":"documents","profile-employment":"employment"};
const addLabels={education:"Add Education",experience:"Add Experience",certifications:"Add Certification",references:"Add Reference"};
function Card({id,title,icon,children,note,editTarget}){
 const context=useContext(SectionContext),key=sectionKeys[id],missing=context.progress.remaining.filter(item=>item.section===id);
 const editing=Boolean(key && context.editing?.section===key);
 if(context.visibleSections&&!context.visibleSections.includes(id))return null;
 return <section id={id} className={`profile-information-card ${missing.length?"profile-needs-details":""}`}><header><span>{icon}</span><div><h2>{title}</h2>{note&&<p>{note}</p>}{missing.length>0&&<p className="profile-required-warning">Action needed: {missing.length} missing {missing.length===1?"item":"items"}. Please complete this section.</p>}</div>{context.canEdit&&key&&(key!=="employment"||context.canManageDocuments)&&<div className="profile-section-actions">{addLabels[key]&&<button type="button" onClick={()=>context.open(key,true)}>{addLabels[key]}</button>}<button type="button" aria-label={key==="documents"?"Add / Update Documents":"Edit "+title} onClick={()=>context.open(key,false)}>{key==="documents"?"Add / Update Documents":"Edit"}</button></div>}{context.canEdit&&editTarget&&<div className="profile-section-actions"><button type="button" aria-label={"Edit "+title} onClick={()=>{context.open(editTarget);window.requestAnimationFrame(()=>document.getElementById("profile-"+editTarget)?.scrollIntoView?.({behavior:"smooth",block:"start"}))}}>Edit</button></div>}</header>{editing?<EmployeeFormModal key={key+String(context.editing.add)} employee={context.employee} selfService={!context.canManageDocuments} inline editSection={key==="employment"?"all":key} addEntry={context.editing.add} onClose={()=>context.setEditing(null)} onSaved={message=>{context.setEditing(null);context.onSaved?.(message)}}/>:children}</section>;
}
export default function EmployeeProfileInformation({employee,canEdit,onEdit,canManageDocuments,onSaved,overview,visibleSections,onNavigateSection}){
 const c=normalizeCollection(employee.collection),p=employee.payroll_profile||{},progress=employeeProfileCompletion(employee);
 const [editing,setEditing]=useState(null);
 const open=(section,add=false)=>{onNavigateSection?.(Object.keys(sectionKeys).find(id=>sectionKeys[id]===section));setEditing({section,add});};
 const [busy,setBusy]=useState(""),[error,setError]=useState("");
 const documentLabel=category=>{for(const [i,row] of c.education.entries()){if(category===`education_${row.id}_certificate`)return `${row.degree||"Qualification "+(i+1)} - Certificate`;if(category===`education_${row.id}_marksheets`)return `${row.degree||"Qualification "+(i+1)} - Marksheets`;}for(const row of c.employment)if(category===`experience_${row.id}`)return `${row.company||"Previous employer"} - Experience Letter`;for(const row of c.certifications)if(category===`certification_${row.id}`)return row.name||"Certification";return category.replace(/_/g," ")};
 const download=async doc=>{setBusy(doc.id);setError("");try{await downloadEmployeeDocument(employee.id,doc.id,doc.name)}catch{setError("Document could not be downloaded. Please try again.")}finally{setBusy("")}};
 return <SectionContext.Provider value={{employee,canEdit,canManageDocuments,progress,editing,setEditing,open,onSaved,visibleSections}}><div className="profile-information-layout"><Card id="profile-completion" title="Profile Completion" icon={<FaChartPie/>} note="Based on personal, family, banking and qualification details. Optional references and achievements do not lower your score."><div className="profile-completion-summary"><div className="profile-completion-ring" style={{"--completion":progress.percentage+"%"}} role="progressbar" aria-label="Profile completion" aria-valuemin={0} aria-valuemax={100} aria-valuenow={progress.percentage}><strong>{progress.percentage}%</strong><small>Complete</small></div><div><h3>{progress.percentage===100?"Your profile is complete":"Keep your profile up to date"}</h3><p>{progress.completed} of {progress.total} items completed. {progress.remaining.length} remaining.</p>{canEdit&&<button type="button" className="profile-primary-action" onClick={()=>{open("personal");onEdit?.("personal")}}>Update Profile</button>}</div></div>{progress.remaining.length>0&&<details className="profile-remaining"><summary>View remaining items ({progress.remaining.length})</summary><ul>{progress.remaining.map(item=><li key={item.label}><a onClick={()=>onNavigateSection?.(item.section)} href={"#"+item.section}>{item.label}</a></li>)}</ul></details>}</Card>
 <Card id="profile-details" title="Personal Information" icon={<FaUser/>}><Details rows={[["Full Name",employee.legal_name||[employee.firstname,employee.lastname].filter(Boolean).join(" ")],["Personal Email",c.email||employee.payroll_email],["Phone Number",employee.contact_info],["Date of Birth",employee.birthdate==="0000-00-00"?"":employee.birthdate],["Gender",employee.gender],["Permanent Address",employee.address],["Current Address",c.current_address],["Facebook Profile",c.facebook_profile]]}/></Card>
 <Card id="profile-employment" title="Employment Details" icon={<FaBriefcase/>}><Details rows={[["Employee ID",employee.employee_id],["Department",p.department],["Position",employee.position_name||employee.position||employee.role],["Joining Date",employee.date_of_joining||employee.joining_date],["Employment Type",employee.employment_type||p.employment_type],["Reporting Manager",employee.reporting_manager||p.reporting_manager],["Work Location",p.location],["Status",employee.user_status|| (employee.user_id?"Assigned":"Not Assigned")]]}/></Card>
 <Card id="profile-skills" title="Skills" editTarget="certifications" icon={<FaCertificate/>}><div className="reference-skills-tags">{[...new Set(c.education.map(row=>row.branch).concat(c.certifications.map(row=>row.name)).filter(Boolean))].map(skill=><span key={skill}>{skill}</span>)}</div><h3>Qualifications & Certifications</h3><p>{c.education.length} qualifications · {c.certifications.length} certifications</p><a onClick={()=>onNavigateSection?.("profile-certifications")} href="#profile-certifications">View / update certifications</a><p className="reference-skills-note">Skill proficiency ratings have not been recorded.</p></Card>
 {overview}
 <Card id="profile-family" title="Family Details" icon={<FaUsers/>}><Details rows={[["Father's Name",c.father_name],["Father's Phone",c.father_phone],["Mother's Name",c.mother_name],["Mother's Phone",c.mother_phone]]}/>{c.siblings.length>0&&<div className="profile-entry-list">{c.siblings.map((row,i)=><article key={i}><h3>{row.name||`Sibling ${i+1}`}</h3><Details rows={[["Relationship",row.relationship],["Phone",row.phone]]}/></article>)}</div>}</Card>
 <Card id="profile-bank" title="Banking & Statutory Details" icon={<FaFileAlt/>}><Details rows={[["Bank Name",p.bank_name],["Account Number",p.bank_account_number],["IFSC Code",p.ifsc_code],["Pay Mode",p.pay_mode],["PAN",p.pan_number],["UAN",p.uan_number],["PF Account",p.pf_account_number],["ESI Account",p.esi_number]]}/></Card>
 <Card id="profile-education" title="Education" icon={<FaGraduationCap/>} note="Qualifications, starting with the highest degree.">{c.education.length?<div className="profile-entry-list">{c.education.map(row=><article key={row.id}><h3>{row.degree||"Qualification"}</h3><Details rows={[["College / School",row.college],["Branch",row.branch],["Year of Passing",row.passing_year]]}/></article>)}</div>:<p className="profile-empty">No qualifications added yet.</p>}</Card>
 <Card id="profile-experience" title="Work Experience" icon={<FaBriefcase/>}>{c.has_experience&&c.employment.length?<div className="profile-entry-list">{c.employment.map(row=><article key={row.id}><h3>{row.company||"Previous Employer"}</h3><Details rows={[["Designation",row.designation],["Employment Period",row.period]]}/></article>)}</div>:<p className="profile-empty">No previous work experience declared.</p>}</Card>
 <Card id="profile-certifications" title="Certifications & Achievements" icon={<FaCertificate/>}>{c.certifications.length?<div className="profile-entry-list">{c.certifications.map(row=><article key={row.id}><h3>{row.name||"Certification"}</h3><Details rows={[["Issuer",row.issuer],["Year",row.year]]}/></article>)}</div>:<p className="profile-empty">No certifications added yet.</p>}<Details rows={[["Professional Certifications",c.professional_certifications],["Achievements",c.achievements]]}/></Card>
 <Card id="profile-references" title="References" icon={<FaUsers/>}>{c.references.length?<div className="profile-entry-list">{c.references.map(row=><article key={row.id}><h3>{row.name||"Reference"}</h3><Details rows={[["Relationship",row.relationship],["Organization",row.organization],["Phone",row.phone],["Email",row.email]]}/></article>)}</div>:<p className="profile-empty">No references added. This section is optional.</p>}</Card>
 <Card id="profile-documents" title="Documents" icon={<FaFileAlt/>} note={canManageDocuments?"You have permission to submit corrected document versions through Edit Employee.":"Uploaded documents are locked. Contact a user with employee-edit permission for corrections. You may still upload missing documents."}>{c.documents.length?<div className="profile-document-list">{c.documents.map(doc=><article key={doc.id}><span><FaFileAlt/></span><div><h3>{documentLabel(doc.category)}</h3><p>{doc.name}</p><small>Uploaded{doc.uploaded_at?` | ${new Date(doc.uploaded_at).toLocaleDateString()}`:""}{doc.size?` | ${(doc.size/1048576).toFixed(2)} MB`:""}</small></div><button type="button" disabled={Boolean(busy)} aria-label={"Download "+doc.name} onClick={()=>download(doc)}><FaDownload/>{busy===doc.id?"Downloading...":"Download"}</button></article>)}</div>:<p className="profile-empty">No documents uploaded yet.</p>}{error&&<p role="alert" className="collection-error">{error}</p>}</Card>
 <Card id="profile-declaration" title="Declaration" icon={<FaCheckCircle/>}><p className="profile-declaration-status">{c.declaration.accepted?"Confirmed by the candidate":"Not confirmed yet"}</p><p>I confirm that the information and documents provided are accurate and complete to the best of my knowledge and may be reviewed for verification purposes.</p>{c.declaration.accepted_at&&<small>Confirmed {new Date(c.declaration.accepted_at).toLocaleDateString()}</small>}</Card>
 </div></SectionContext.Provider>;
}
