import {render,screen,fireEvent,waitFor} from "@testing-library/react";
import EmployeeProfileInformation from "./EmployeeProfileInformation";
import {getEmployeeById,updateMyEmployeeProfile} from "../api/employeeApi";
import {emptyCollection} from "../utils/employeeCollection";
import {employeeProfileCompletion} from "../utils/employeeProfileCompletion";
jest.mock("../api/employeeApi",()=>({downloadEmployeeDocument:jest.fn(),getEmployeeById:jest.fn(),updateMyEmployeeProfile:jest.fn(),getPositions:jest.fn()}));
test("profile displays information cards without form controls and separates documents",async()=>{
 const collection=emptyCollection();collection.education=[{id:"degree1",degree:"B.Tech",college:"Saved College",branch:"CSE",passing_year:"2020"}];collection.documents=[{id:"doc1",category:"education_degree1_certificate",name:"degree.pdf"}];const edit=jest.fn();getEmployeeById.mockResolvedValue({data:{id:7,firstname:"Test",lastname:"Employee",collection}});render(<EmployeeProfileInformation employee={{id:7,firstname:"Test",lastname:"Employee",employee_id:"BDT-I-133",collection}} canEdit onEdit={edit}/>);
 expect(screen.getByRole("heading",{name:"Personal Information"})).toBeInTheDocument();expect(screen.getByRole("heading",{name:"Education"})).toBeInTheDocument();expect(screen.getByRole("heading",{name:"Documents"})).toBeInTheDocument();expect(screen.getByText("Saved College")).toBeInTheDocument();expect(screen.queryByRole("textbox")).not.toBeInTheDocument();expect(screen.queryByRole("combobox")).not.toBeInTheDocument();expect(screen.getByRole("progressbar",{name:"Profile completion"})).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"Update Profile"}));expect(edit).toHaveBeenCalled();await waitFor(()=>expect(screen.getByRole("button",{name:"Save Changes"})).toBeEnabled());
});
test("completion updates when missing details and documents are added",()=>{
 const collection=emptyCollection();collection.education=[{id:"degree1",degree:"B.Tech",college:"College",passing_year:"2020"}];const employee={firstname:"Test",lastname:"Employee",collection};const before=employeeProfileCompletion(employee);collection.documents=[{id:"doc1",category:"education_degree1_certificate",name:"degree.pdf"}];employee.contact_info="123";const after=employeeProfileCompletion(employee);expect(after.completed).toBe(before.completed+2);expect(after.remaining.some(item=>item.label==="Qualification 1: certificate")).toBe(false);expect(after.remaining.some(item=>item.label==="Qualification 1: marksheets")).toBe(true);
});


test("adds education inside its own card without unrelated personal fields",async()=>{
 const collection=emptyCollection();collection.education=[];const employee={id:7,employee_id:"BDT-I-133",firstname:"Test",lastname:"Employee",birthdate:"1995-01-01",gender:"Female",address:"Saved address",contact_info:"123",collection};getEmployeeById.mockResolvedValue({data:employee});updateMyEmployeeProfile.mockResolvedValue({success:true,message:"Education saved"});const saved=jest.fn();render(<EmployeeProfileInformation employee={employee} canEdit onSaved={saved}/>);
 fireEvent.click(screen.getByRole("button",{name:"Add Education"}));await screen.findByLabelText(/^Degree \/ Qualification/);expect(screen.queryByLabelText(/^First Name/)).not.toBeInTheDocument();expect(screen.queryByRole("dialog")).not.toBeInTheDocument();
 fireEvent.change(screen.getByLabelText(/^Degree \/ Qualification/),{target:{value:"B.Tech"}});fireEvent.change(screen.getByLabelText(/^College \/ School Name/),{target:{value:"New College"}});fireEvent.change(screen.getByLabelText(/^Year of Passing/),{target:{value:"2020"}});fireEvent.click(screen.getByRole("button",{name:"Save Changes"}));await waitFor(()=>expect(saved).toHaveBeenCalledWith("Education saved"));const payload=JSON.parse(updateMyEmployeeProfile.mock.calls[0][0].get("payload"));expect(payload.edit_section).toBe("education");expect(payload.collection.education[0].college).toBe("New College");expect(payload.address).toBe("Saved address");
});

test("selected personal panel excludes other categories and keeps inline editing",async()=>{const employee={id:7,firstname:"Test",lastname:"Employee",collection:emptyCollection()};getEmployeeById.mockResolvedValue({data:employee});render(<EmployeeProfileInformation employee={employee} canEdit visibleSections={["profile-details"]}/>);expect(screen.getByRole("heading",{name:"Personal Information"})).toBeInTheDocument();expect(screen.queryByRole("heading",{name:"Education"})).not.toBeInTheDocument();expect(screen.queryByRole("heading",{name:"Documents"})).not.toBeInTheDocument();expect(screen.queryByRole("progressbar")).not.toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"Edit Personal Information"}));await screen.findByLabelText(/^First Name/);expect(screen.queryByLabelText(/^College/)).not.toBeInTheDocument()});

test("inline editors open from the loaded record without waiting for a second API request",async()=>{const employee={id:7,firstname:"Already",lastname:"Loaded",collection:emptyCollection()};getEmployeeById.mockImplementation(()=>new Promise(()=>{}));render(<EmployeeProfileInformation employee={employee} canEdit visibleSections={["profile-details"]}/>);fireEvent.click(screen.getByRole("button",{name:"Edit Personal Information"}));expect(screen.getByLabelText(/^First Name/)).toHaveValue("Already");expect(screen.getByRole("button",{name:"Save Changes"})).toBeEnabled();expect(getEmployeeById).not.toHaveBeenCalled();expect(screen.queryByText(/Loading complete/)).not.toBeInTheDocument();});

 test("only banking details are masked, with independent reveal controls and original edit values",async()=>{
 const collection=emptyCollection();collection.email="private@example.com";collection.father_name="Father";collection.mother_name="Mother";
 const employee={id:7,employee_id:null,firstname:"Test",lastname:"Employee",birthdate:"1995-01-01",gender:"Female",contact_info:"9876543210",collection,payroll_profile:{pan_number:"ABCDE1234F",bank_account_number:"123456789012",bank_name:"Bank",ifsc_code:"BANK0000001"}};
 render(<EmployeeProfileInformation employee={employee} canEdit/>);
 expect(screen.queryByText("ABCDE1234F")).not.toBeInTheDocument();expect(screen.queryByText("123456789012")).not.toBeInTheDocument();expect(screen.getByText("9876543210")).toBeInTheDocument();expect(screen.getByText("private@example.com")).toBeInTheDocument();expect(screen.getAllByText("XXXXX.XXX......").length).toBe(4);
 fireEvent.click(screen.getByRole("button",{name:"Show PAN"}));expect(screen.getByText("ABCDE1234F")).toBeInTheDocument();expect(screen.getByRole("button",{name:"Hide PAN"})).toHaveAttribute("aria-pressed","true");expect(screen.queryByText("123456789012")).not.toBeInTheDocument();
 fireEvent.click(screen.getByRole("button",{name:"Hide PAN"}));expect(screen.queryByText("ABCDE1234F")).not.toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"Show Account Number"}));expect(screen.getByText("123456789012")).toBeInTheDocument();
 const progress=employeeProfileCompletion(employee);expect(progress.remaining.some(item=>/Permanent address|Father's phone|Mother's phone/.test(item.label))).toBe(false);
 fireEvent.click(screen.getByRole("button",{name:"Edit Banking & Statutory Details"}));expect(await screen.findByLabelText(/^PAN/)).toHaveValue("ABCDE1234F");
 });
