import {FaFileAlt,FaClock,FaChartPie,FaCalendarAlt} from "react-icons/fa";
import {employeeProfileCompletion} from "../utils/employeeProfileCompletion";
import {normalizeCollection} from "../utils/employeeCollection";
const number=value=>value!==null&&value!==undefined&&value!==""&&Number.isFinite(Number(value));
export default function EmployeeProfileOverview({employee,attendance,attendanceError,canViewAttendance,details=false,section}){
 const c=normalizeCollection(employee.collection),summary=attendance?.summary;
 const present=number(summary?.present_days)?Number(summary.present_days):null,hours=number(summary?.total_hours)?Number(summary.total_hours):null,expected=attendance?.working_days??summary?.working_days;
 const percentage=present!==null&&number(expected)&&Number(expected)>0?Math.min(100,Math.round(present/Number(expected)*100)):null;
 const unavailable=canViewAttendance?(attendanceError?"Unavailable":"Loading…"):"Restricted";
 if(!details){const metrics=[["Profile Completion",employeeProfileCompletion(employee).percentage+"%","Required information",FaChartPie,"blue"],["Total Hours",hours!==null?`${hours}h`:unavailable,"This Month",FaClock,"violet"],["Documents",c.documents.length,"Uploaded documents",FaFileAlt,"green"],["Attendance",percentage!==null?`${percentage}%`:present!==null?present:unavailable,percentage!==null?"This Month":"Present this month",FaCalendarAlt,"rose"]];return <div className="reference-metrics">{metrics.map(([label,value,note,Icon,color])=><article className={`reference-metric ${color}`} key={label}><span><Icon/></span><div><p>{label}</p><strong>{value}</strong><small>{note}</small></div></article>)}</div>}
 const joined=employee.date_of_joining||employee.joining_date;
 const events=[...(joined&&Number.isFinite(Date.parse(joined))?[{date:joined,title:`Joined as ${employee.position_name||employee.position||employee.role||"employee"}`}]:[]),...c.documents.filter(d=>d.uploaded_at).map(d=>({date:d.uploaded_at,title:`Uploaded ${d.name}`}))].sort((a,b)=>new Date(a.date)-new Date(b.date)).slice(-4);
 return <>{(!section||section==="profile-attendance")&& <section className="reference-overview-card reference-month"><header><h2>Attendance (This Month)</h2></header>{attendanceError?<p role="alert">{attendanceError}</p>:<div className="reference-month-content"><div className="reference-attendance-donut" style={{"--attendance":(percentage??(present?100:0))+"%"}} role="img" aria-label={percentage!==null?`${percentage}% attendance`:present!==null?`${present} days present`:unavailable}><strong>{percentage!==null?`${percentage}%`:present!==null?present:"—"}</strong><small>{percentage!==null?"Attendance":"Days Present"}</small></div><dl><div><dt>Present</dt><dd>{present??"—"}</dd></div><div><dt>Half Days</dt><dd>{summary?.half_days??"—"}</dd></div><div><dt>Approved Leaves</dt><dd>{attendance?attendance.leaves?.length??0:"—"}</dd></div><div><dt>Total Hours</dt><dd>{hours!==null?`${hours}h`:"—"}</dd></div></dl></div>}</section>}
 {(!section||section==="profile-activity")&&<section id="profile-activity" className="reference-overview-card reference-timeline"><header><h2>Work Timeline</h2></header>{events.length?<ol>{events.map((e,i)=><li key={i}><time>{new Date(e.date).toLocaleDateString()}</time><span>{e.title}</span></li>)}</ol>:<p className="reference-empty">Employment and document activity will appear here.</p>}</section>}{(!section||section==="profile-leave")&&<section id="profile-leave" className="reference-overview-card reference-leave"><header><h2>Approved Leave (This Month)</h2></header>{attendance?.leaves?.length?<ul>{attendance.leaves.map((leave,i)=><li key={leave.id??i}>{leave.leave_type||"Leave"}: {leave.start_date} – {leave.end_date}</li>)}</ul>:<p className="reference-empty">{canViewAttendance?(attendanceError?"Leave records could not be loaded.":attendance?"No approved leave recorded for this month.":"Loading leave records..."):"Attendance permission is required to view leave records."}</p>}</section>}</>;
}