import {useCallback,useEffect,useState} from "react";
import {FaClock,FaRedo} from "react-icons/fa";
import {getTodayAttendance,clockAttendance} from "../api/employeeApi";
import "../styles/employeeProfile.css";
export default function EmployeeAttendanceSwitch({employeeCode,onChanged,compact=false,onViewAttendance}){
 const [today,setToday]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const load=useCallback(async()=>{setLoading(true);try{const result=await getTodayAttendance(undefined,true);setToday(result);setError("")}catch(e){setError(e?.response?.data?.message||"Attendance status could not be loaded.")}finally{setLoading(false)}},[]);
 useEffect(()=>{load()},[load]);
 const record=today?.record,working=Boolean(record&&record.time_out==="00:00:00"),complete=Boolean(record&&!working);
 const toggle=async()=>{if(!employeeCode||busy||loading||!today?.network?.allowed||complete)return;setBusy(true);setError("");setMessage("");try{const result=await clockAttendance(working?"out":"in",employeeCode);if(!result.success)throw new Error(result.message);await load();setMessage(result.message);onChanged?.()}catch(e){setError(e?.response?.data?.message||e.message||"Attendance could not be updated.")}finally{setBusy(false)}};
 if(compact)return <section className="reference-today-card" aria-label="Attendance login and logout"><header><h2>Attendance (Today)</h2><span className={record?"present":"pending"}>{loading?"Loading…":record?"Present":"Not logged in"}</span></header><div className="reference-today-controls"><FaClock/><div><small>{loading?"Loading status...":complete?"Shift completed":working?"Logged in - working":"Logged out"}</small><strong>{record?.time_in||"—"}</strong><time>{today?.work_date||"Today"} · ET</time></div><button type="button" role="switch" aria-checked={working} aria-label="Attendance login" disabled={!employeeCode||busy||loading||!today?.network?.allowed||complete} onClick={toggle}><span className="attendance-toggle-track"><span/></span></button><button type="button" className="reference-shift-label" disabled={!employeeCode||busy||loading||!today?.network?.allowed||complete} onClick={toggle}>{busy?"Saving…":working?"Logout":complete?"Completed":"Login"}<small>Shift</small></button></div><footer><span>{record?.time_out&&record.time_out!=="00:00:00"?`Logged out: ${record.time_out} ET`:"Company network required"}</span><button type="button" onClick={onViewAttendance}>View Attendance →</button></footer>{!loading&&today&&!today.network?.allowed&&<p className="employee-network-note">Company network required. Current IP: {today.network?.ip||"unavailable"}. Approved WFH exceptions are supported.</p>}{!employeeCode&&<p className="employee-network-note">HR must assign your employee ID before attendance login is available.</p>}{error&&<p role="alert" className="collection-error">{error}<button type="button" disabled={busy||loading} onClick={load}><FaRedo/> Refresh Status</button></p>}{message&&<p role="status">{message}</p>}</section>;
 return <section className="employee-attendance-switch" aria-label="Attendance login and logout"><div className="employee-shift-heading"><FaClock/><div><h2>Attendance Login / Logout</h2><p>{today?.work_date||"Today"} | Eastern Time</p></div></div><div className="employee-shift-control"><span><strong>{loading?"Loading status...":complete?"Shift completed":working?"Logged in - working":"Logged out"}</strong><small>{working?`Login: ${record.time_in} ET`:complete?`${record.time_in} - ${record.time_out} ET`:"Start your shift from the company network."}</small></span><button type="button" role="switch" aria-checked={working} aria-label="Attendance login" disabled={!employeeCode||busy||loading||!today?.network?.allowed||complete} onClick={toggle}><span className="attendance-toggle-track"><span/></span><b>{busy?"Saving...":working?"Logout":"Login"}</b></button></div>{!loading&&today&&!today.network?.allowed&&<p className="employee-network-note">Company network required. Current IP: {today.network?.ip||"unavailable"}. Approved WFH exceptions are supported.</p>}{!employeeCode&&<p className="employee-network-note">HR must assign your employee ID before attendance login is available.</p>}{error&&<p role="alert" className="collection-error">{error} <button type="button" disabled={busy||loading} onClick={load}><FaRedo/> Refresh Status</button></p>}{message&&<p role="status" className="attendance-config-success">{message}</p>}</section>;
}
