import {useEffect,useRef,useState} from "react";
import {createPortal} from "react-dom";
import {FaDownload,FaTimes,FaUser} from "react-icons/fa";
import {getEmployeePhoto} from "../api/employeeApi";
import {employeeIdCardDetails,downloadEmployeeIdCard} from "../utils/employeeIdCard";
import logo from "../assets/beedata-logo.png";
import "../styles/employeeIdCard.css";
export default function EmployeeIdCard({employee,onClose}){
 const details=employeeIdCardDetails(employee),[photo,setPhoto]=useState(''),[qr,setQr]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('');const dialog=useRef(null);
 useEffect(()=>{let active=true,url='';const previous=document.activeElement;dialog.current?.querySelector('button')?.focus();const load=async()=>{try{const QRCode=await import('qrcode');const verification=new URL(`/dashboard/employee-status/${employee.id}`,window.location.origin).href;const code=await QRCode.toDataURL(verification,{width:600,margin:1,errorCorrectionLevel:'M'});let portrait='';if(employee.photo){const blob=await getEmployeePhoto(employee.id);if(!active)return;url=URL.createObjectURL(blob);portrait=url;}else portrait=employee.profile_photo_url||'';if(active){setQr(code);setPhoto(portrait)}}catch(e){if(active)setError('The ID card assets could not be loaded. Close and reopen to retry.')}finally{if(active)setLoading(false)}};load();return()=>{active=false;if(url)URL.revokeObjectURL(url);if(previous?.isConnected)previous.focus({preventScroll:true})}},[employee.id,employee.photo,employee.profile_photo_url]);
 const download=async()=>{setBusy(true);setError('');try{const img=new Image();img.src=logo;await img.decode();const canvas=document.createElement('canvas');canvas.width=img.width;canvas.height=img.height;canvas.getContext('2d').drawImage(img,0,0);await downloadEmployeeIdCard(details,photo,qr,canvas.toDataURL('image/png'));}catch(e){setError('PDF could not be generated. Please try again.')}finally{setBusy(false)}};
 const art=<><div className="id-card-top-art"/><div className="id-card-bottom-art"/></>;
 return createPortal(<div className="employee-id-overlay" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)onClose()}}><section className="employee-id-dialog" ref={dialog} role="dialog" aria-modal="true" aria-labelledby="employee-id-title" onKeyDown={e=>{if(e.key==='Escape'&&!busy)onClose();if(e.key==='Tab'){const controls=[...dialog.current.querySelectorAll('button:not(:disabled)')],first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}}><header><div><h2 id="employee-id-title">Employee ID Card</h2><p>{details.name} &bull; {details.id}</p></div><button disabled={busy} aria-label="Close ID card" onClick={onClose}><FaTimes/></button></header><div className="employee-id-preview"><div><p className="id-card-side-label">Front</p><article className="employee-id-card">{art}<div className="id-card-brand"><img src={logo} alt="BeeData"/><strong>BEEDATA TECHNOLOGIES</strong></div><div className="id-card-photo">{photo?<img src={photo} alt={details.name}/>:<FaUser/>}</div><h3>{details.name}</h3><p className="id-card-role">{details.role}</p><strong className="id-card-number">{details.id}</strong><dl>{[['Joined',details.joined],['Location',details.location]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><div className="id-card-qr">{qr&&<img src={qr} alt="Employee profile verification QR"/>}<small>Scan to Verify</small></div></article></div><div><p className="id-card-side-label">Back</p><article className="employee-id-card id-card-back">{art}<div className="id-card-brand"><strong>BEEDATA TECHNOLOGIES</strong></div><div className="id-card-back-copy"><h3>Employee Information</h3><p><b>Employee ID:</b> {details.id}</p><p>This card is the property of BeeData Technologies.</p><p>If found, please return to:<br/><b>BeeData Technologies</b></p><p>Email: hr_ind@bedatatech.com<br/>Website: beedatatech.com</p><p><b>Emergency Contact:</b><br/>HR Department</p></div><div className="id-card-back-footer">{qr&&<img src={qr} alt="Verification QR"/>}<span>Authorized Signature</span></div></article></div></div>{error&&<p className="employee-id-error" role="alert">{error}</p>}<footer><small>QR verification requires an authorized login.</small><button disabled={busy||loading||Boolean(error&&!qr)} onClick={download}><FaDownload/>{busy?'Generating PDF...':loading?'Loading card...':'Download PDF'}</button></footer></section></div>,document.body);
}
