import {useEffect,useRef,useState} from "react";
import {FaCamera,FaUser,FaTrashAlt} from "react-icons/fa";
import {createPortal} from "react-dom";
import {FaTimes,FaCloudUploadAlt} from "react-icons/fa";
import {getEmployeePhoto,uploadEmployeePhoto,removeEmployeePhoto} from "../api/employeeApi";
import ConfirmDialog from "./ConfirmDialog";
export default function EmployeeProfilePhoto({employee,canEdit,onSaved}){
 const [source,setSource]=useState(employee.profile_photo_url||""),[editing,setEditing]=useState(false),[file,setFile]=useState(null),[preview,setPreview]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const [removing,setRemoving]=useState(false);
 const maxPhotoBytes=Math.min(2097152,employee.upload_limits?.max_file_bytes||2097152,employee.upload_limits?.max_total_bytes||2097152);
 const photoLimit=(maxPhotoBytes/1048576).toFixed(1);
 const picker=useRef(null),savedUrl=useRef(""),trigger=useRef(null),dialog=useRef(null);
 useEffect(()=>{if(!editing)return;const previous=document.activeElement;picker.current?.focus();const handle=event=>{if(event.key==="Escape"&&!busy){setEditing(false);setFile(null);setError("");}if(event.key==="Tab"){const controls=Array.from(dialog.current?.querySelectorAll("button:not(:disabled),input:not(:disabled)")||[]);if(!controls.length){event.preventDefault();return;}const first=controls[0],last=controls[controls.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus()}}};document.addEventListener("keydown",handle);return()=>{document.removeEventListener("keydown",handle);previous?.focus?.()}},[editing,busy]);
 useEffect(()=>{let active=true;let url="";if(savedUrl.current){URL.revokeObjectURL(savedUrl.current);savedUrl.current="";}setSource(employee.profile_photo_url||"");if(employee.photo)getEmployeePhoto(employee.id).then(blob=>{if(active&&!savedUrl.current){url=URL.createObjectURL(blob);setSource(url)}}).catch(()=>{});return()=>{active=false;if(url)URL.revokeObjectURL(url)}},[employee.id,employee.photo,employee.profile_photo_url]);
 useEffect(()=>{if(!file){setPreview("");return}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url)},[file]);
 useEffect(()=>()=>{if(savedUrl.current)URL.revokeObjectURL(savedUrl.current)},[]);
 const select=event=>{const chosen=event.target.files?.[0];setError("");if(!chosen)return;if(!["image/jpeg","image/png","image/webp"].includes(chosen.type)||chosen.size>maxPhotoBytes||!chosen.size){setFile(null);event.target.value="";setError(`Choose a JPG, PNG or WebP image up to ${photoLimit} MB.`);return}setFile(chosen)};
 const cancel=()=>{setEditing(false);setFile(null);setError("")};
 const save=async event=>{event.preventDefault();if(!file||busy)return;setBusy(true);setError("");try{const result=await uploadEmployeePhoto(employee.id,file);if(!result.success)throw Error(result.message||"Photo could not be saved.");if(savedUrl.current)URL.revokeObjectURL(savedUrl.current);savedUrl.current=URL.createObjectURL(file);setSource(savedUrl.current);setMessage("Profile photo updated.");window.dispatchEvent(new CustomEvent("e2e-profile-photo-changed",{detail:{employeeId:employee.id}}));cancel();onSaved?.(result.message||"Profile photo updated.")}catch(e){setError(e?.response?.data?.message||e.message||"Photo could not be saved. Please try again.")}finally{setBusy(false)}};
 const remove=async()=>{if(busy)return;setBusy(true);setError("");try{const result=await removeEmployeePhoto(employee.id);if(!result.success)throw Error(result.message);if(savedUrl.current){URL.revokeObjectURL(savedUrl.current);savedUrl.current="";}setSource("");setRemoving(false);setMessage("Profile photo removed.");window.dispatchEvent(new CustomEvent("e2e-profile-photo-changed",{detail:{employeeId:employee.id,removed:true}}));onSaved?.(result.message);}catch(e){setError(e?.response?.data?.message||e.message||"Photo could not be removed.");}finally{setBusy(false);}};
 return <div className="profile-photo-control"><div className="e2e_record_avatar">{source?<img src={source} alt={employee.legal_name||"Employee"} onError={()=>setSource("")}/>:<FaUser/>}</div>{canEdit&&<div className="profile-photo-actions"><button type="button" ref={trigger} className="profile-photo-change" disabled={busy} onClick={()=>{setEditing(value=>!value);setError("");setMessage("")}} aria-expanded={editing} aria-label={source?"Update profile photo":"Add profile photo"}><FaCamera/> <span>{source?"Update":"Add"}<span className="profile-photo-word"> Photo</span></span></button>{source&&<button type="button" className="profile-photo-remove" disabled={busy} aria-label="Remove profile photo" title="Remove photo" onClick={()=>{setError("");setRemoving(true);}}><FaTrashAlt/></button>}</div>}{editing&&createPortal(<div className="profile-photo-overlay" onMouseDown={event=>{if(event.target===event.currentTarget&&!busy)cancel()}}><section ref={dialog} className="profile-photo-dialog" role="dialog" aria-modal="true" aria-labelledby="profile-photo-title"><header><div><FaCamera/><h2 id="profile-photo-title">Update profile portrait</h2></div><button type="button" aria-label="Close photo editor" disabled={busy} onClick={cancel}><FaTimes/></button></header><form className="profile-photo-editor" aria-label="Edit profile photo" onSubmit={save}>{preview&&<img src={preview} alt="Portrait preview"/>}<label className="profile-photo-picker"><FaCloudUploadAlt/><strong>Choose profile photo</strong><span>Select a JPG, PNG or WebP image</span><input ref={picker} aria-label="Choose profile photo" type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={select}/></label><p>JPG, PNG or WebP. Maximum {photoLimit} MB.</p>{error&&<p role="alert">{error}</p>}<footer><button type="button" onClick={cancel} disabled={busy}>Cancel</button><button type="submit" disabled={!file||busy}>{busy?"Saving...":"Save Photo"}</button></footer></form></section></div>,document.body)}<ConfirmDialog open={removing} title="Remove profile photo?" message="Your profile will show the default avatar until you add another photo." confirmLabel="Remove Photo" busy={busy} onCancel={()=>setRemoving(false)} onConfirm={remove}>{error&&<p role="alert" className="collection-error">{error}</p>}</ConfirmDialog>{message&&<span className="e2e_sr_only" role="status">{message}</span>}</div>;
}
