import {normalizeCollection} from "./employeeCollection";
export function employeeIdCardDetails(employee){const c=normalizeCollection(employee.collection),joined=employee.date_of_joining||employee.joining_date,role=employee.position_name||employee.position||employee.role||"Not assigned";return {name:employee.legal_name||[employee.firstname,employee.lastname].filter(Boolean).join(" ")||"Employee",id:employee.employee_id||"Not assigned",role,department:role,joined:joined&&/^\d{4}-\d{2}-\d{2}$/.test(joined)&&joined!=="0000-00-00"?new Date(joined+"T00:00:00").toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"numeric"}):"Not recorded",location:c.current_address?.trim()||"Not recorded"};}
export async function createEmployeeIdCardPdf(details,photo,qr,logo){
 const {jsPDF}=await import("jspdf");const pdf=new jsPDF({orientation:"portrait",unit:"mm",format:[54,85.6],compress:true});
 const text=(value,x,y,size=7,align="left",maxWidth=46)=>{pdf.setFontSize(size);pdf.setTextColor(25,25,25);const lines=pdf.splitTextToSize(String(value),maxWidth);pdf.text(lines,x,y,{align});};
 const box=(value,x,y,width,height,size=7,align='left')=>{let font=size,lines;do{pdf.setFontSize(font);lines=pdf.splitTextToSize(String(value),width);if(lines.length*font*.4<=height)break;font-=.2;}while(font>2);pdf.setTextColor(25,25,25);pdf.text(lines,x,y,{align,lineHeightFactor:1.12});};
 const art=()=>{pdf.setFillColor('#ffffff');pdf.rect(0,0,54,85.6,'F');pdf.setFillColor('#960854');pdf.rect(0,0,54,1.8,'F');pdf.setFillColor('#171717');pdf.lines([[54,15],[0,2],[-54,-15]],0,1.8,[1,1],'F',true);pdf.setFillColor('#e1e1e1');pdf.lines([[54,15],[0,1],[-54,-15]],0,3.8,[1,1],'F',true);pdf.setFillColor('#960854');pdf.lines([[54,0],[0,4],[-54,-4]],0,81.6,[1,1],'F',true);pdf.setFillColor('#171717');pdf.lines([[20,4],[-20,0]],0,81.6,[1,1],'F',true);};
 const image=async source=>{if(!source)return null;const img=new Image();img.src=source;await img.decode();const canvas=document.createElement('canvas');canvas.width=800;canvas.height=800;const c=canvas.getContext('2d');c.fillStyle='#fff';c.fillRect(0,0,800,800);const scale=Math.max(800/img.width,800/img.height);c.drawImage(img,(800-img.width*scale)/2,(800-img.height*scale)/2,img.width*scale,img.height*scale);return canvas.toDataURL('image/jpeg',.96);};
 const portrait=await image(photo);art();pdf.setFillColor('#ffffff');pdf.roundedRect(12,3,30,13,1,1,'F');if(logo)pdf.addImage(logo,'PNG',14,3.5,26,8.6);pdf.setFont('helvetica','bold');pdf.setTextColor('#960854');pdf.setFontSize(6.5);pdf.text('BEEDATA TECHNOLOGIES',27,15,{align:'center'});
 pdf.setFillColor('#edf3f9');pdf.roundedRect(15.5,18,23,23,1.5,1.5,'F');if(portrait)pdf.addImage(portrait,'JPEG',16.5,19,21,21);else text('PHOTO',27,31,7,'center');
 pdf.setFont('helvetica','bold');box(details.name.toUpperCase(),27,45,46,5,8.5,'center');pdf.setFont('helvetica','normal');box(details.role,27,50,46,4,7,'center');pdf.setFillColor('#960854');pdf.roundedRect(4,53,46,6.5,1,1,'F');pdf.setTextColor('#ffffff');pdf.setFont('helvetica','bold');pdf.setFontSize(8);pdf.text(details.id,27,57.4,{align:'center'});pdf.setFont('helvetica','normal');text('Joined: '+details.joined,5,64,6.5);box('Location: '+details.location,5,68,44,7,6.2);if(qr)pdf.addImage(qr,'PNG',22.5,73,9,9);pdf.setFillColor('#ffffff');pdf.rect(19,82.2,16,3,'F');text('Scan to Verify',27,84.3,4.6,'center');
 pdf.addPage([54,85.6],'portrait');art();pdf.setFillColor('#ffffff');pdf.roundedRect(12,3,30,13,1,1,'F');if(logo)pdf.addImage(logo,'PNG',14,3.5,26,8.6);pdf.setFont('helvetica','bold');pdf.setTextColor('#960854');pdf.setFontSize(6.5);pdf.text('BEEDATA TECHNOLOGIES',27,15,{align:'center'});text('EMPLOYEE INFORMATION',5,24,7);pdf.setFillColor('#eff5fb');pdf.roundedRect(4,27,46,7,1,1,'F');text(details.id,27,31.6,8,'center');pdf.setFont('helvetica','normal');text('This card is the property of BeeData Technologies.',5,41,6.5,'left',44);text('If found, please return to BeeData Technologies.',5,51,6.5,'left',44);text('Email: hr_ind@bedatatech.com',5,61,6.1);text('Website: beedatatech.com',5,65,6.1);text('Emergency Contact: HR Department',5,70,5.9);pdf.setFillColor('#ffffff');pdf.rect(3,74,48,10,'F');if(qr)pdf.addImage(qr,'PNG',5,75,9,9);text('Authorized Signature',35,82,5.5,'center',29);pdf.setDrawColor('#99a9bd');pdf.line(22,78,49,78);pdf.setProperties({title:`Employee ID Card - ${details.id}`,subject:'BeeData Technologies Employee Identification',author:'BeeData Technologies'});return pdf;
}

export async function downloadEmployeeIdCard(details,photo,qr,logo){const pdf=await createEmployeeIdCardPdf(details,photo,qr,logo);pdf.save(`ID-Card-${details.id.replace(/[^a-z0-9_-]/gi,'_')}.pdf`);}
