import {useCallback,useEffect,useRef,useState} from 'react';
import {FaBell,FaComments,FaExternalLinkAlt,FaShieldAlt,FaTimes} from 'react-icons/fa';
import {createConversation,getNotificationCenter,markAllNotificationsRead,markNotificationRead} from '../../api/chatApi';
import {usePermissions} from '../../auth/PermissionContext';
const contextFrom=(pathname,title)=>{const parts=pathname.split('/').filter(Boolean).slice(1),records=parts[0]==='records',rawType=records?(parts[1]||'record'):(parts[0]||'dashboard'),type=rawType.replace(/s$/,'').replace(/[^a-z0-9_-]/gi,'_').toLowerCase(),id=(records?parts.slice(2):parts.slice(1)).join(':')||'home';return {type,id,title:title||rawType,url:pathname}};
export default function HeaderCollaboration({location,navigate,title}){
 const {can}=usePermissions(),wrap=useRef(null),[open,setOpen]=useState(false),[confirm,setConfirm]=useState(null),[state,setState]=useState({items:[],unread:0}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=useCallback(async(silent=false)=>{try{setState(await getNotificationCenter());if(!silent)setError('')}catch(e){if(!silent)setError(e?.response?.data?.message||'Notifications are unavailable.')}},[]);
 useEffect(()=>{load(true);const timer=setInterval(()=>document.visibilityState==='visible'&&load(true),15000);return()=>clearInterval(timer)},[load]);
 useEffect(()=>{const close=e=>{if(!wrap.current?.contains(e.target)){setOpen(false);setConfirm(null)}};document.addEventListener('mousedown',close);return()=>document.removeEventListener('mousedown',close)},[]);
 if(!can('chat','view'))return null;
 const requestDiscussion=()=>{setOpen(false);setError('');setConfirm(contextFrom(location.pathname,title))};
 const discuss=async()=>{if(!confirm)return;setBusy(true);setError('');try{const result=await createConversation({type:'contextual',name:`${title} Discussion`,member_ids:[],context:confirm});setConfirm(null);navigate(`/dashboard/chat?conversation=${result.id}`)}catch(e){setError(e?.response?.data?.message||'You do not have permission to open this discussion.')}finally{setBusy(false)}};
 const visit=async item=>{if(!Number(item.is_read))await markNotificationRead(item.id).catch(()=>{});setOpen(false);load(true);navigate(item.destination_url||`/dashboard/chat?conversation=${item.conversation_id}`)};
 const readAll=async()=>{await markAllNotificationsRead();load(true)},orderedItems=[...state.items].sort((a,b)=>Number(b.is_read)-Number(a.is_read)||new Date(b.created_at.replace(' ','T'))-new Date(a.created_at.replace(' ','T'))),showDiscuss=can('chat','create')&&!location.pathname.startsWith('/dashboard/chat')&&!location.pathname.startsWith('/dashboard/notifications');
 return <div className="e2e_collaboration_controls" ref={wrap}>{showDiscuss&&<button type="button" className="e2e_navbar_discuss" onClick={requestDiscussion} disabled={busy} title="Open this resource discussion"><FaComments/><span>Discuss</span></button>}<button type="button" className="e2e_navbar_notification" onClick={()=>{setOpen(v=>!v);setConfirm(null);load(true)}} title="Notifications" aria-label={`Notifications${state.unread?`, ${state.unread} unread`:''}`} aria-expanded={open}><FaBell/>{state.unread>0&&<b>{state.unread>99?'99+':state.unread}</b>}</button>{open&&<section className="e2e_notification_center" role="dialog" aria-label="Notifications"><header><div><strong>Notifications</strong><small>{state.unread} unread</small></div>{state.unread>0&&<button onClick={readAll}>Mark all read</button>}</header>{error&&<p className="e2e_notification_error">{error}</p>}<div>{orderedItems.length?orderedItems.map(item=><button type="button" className={`e2e_notification_item ${Number(item.is_read)?'':'unread'}`} key={item.id} onClick={()=>visit(item)}><span><FaComments/></span><span><strong>{item.title}</strong><small>{item.body||'Open the related discussion'}</small><time>{new Date(item.created_at.replace(' ','T')).toLocaleString()}</time></span><FaExternalLinkAlt/></button>):<p className="e2e_notification_empty">No notifications yet.</p>}</div><button className="e2e_notification_all" onClick={()=>{setOpen(false);navigate('/dashboard/notifications')}}>View all discussions and notifications</button></section>}{confirm&&<div className="e2e_discussion_confirm" onMouseDown={()=>!busy&&setConfirm(null)}><section role="dialog" aria-modal="true" aria-labelledby="discussion-confirm-title" onMouseDown={e=>e.stopPropagation()}><header><span><FaComments/></span><button type="button" onClick={()=>setConfirm(null)} aria-label="Close"><FaTimes/></button></header><small>RESOURCE DISCUSSION</small><h2 id="discussion-confirm-title">Open discussion?</h2><p>Collaborate about <strong>{confirm.title}</strong> with its authorized workflow participants.</p><div className="e2e_discussion_context"><FaShieldAlt/><span><strong>Permission controlled</strong><small>The existing discussion is reused. A new empty discussion is removed automatically if nobody sends a message.</small></span></div>{error&&<p className="e2e_discussion_confirm_error">{error}</p>}<footer><button type="button" className="secondary" disabled={busy} onClick={()=>setConfirm(null)}>Cancel</button><button type="button" disabled={busy} onClick={discuss}><FaComments/> {busy?'Opening…':'Open discussion'}</button></footer></section></div>}</div>;
}