from pathlib import Path
root=Path.cwd()
p=root/'src/pages/Dashboard/EmployeeView.js'
s=p.read_text(encoding='utf-8')
s=s.replace('FaUserTag }','FaUserTag, FaEnvelope, FaPhone, FaMapMarkerAlt, FaCalendarAlt, FaHome, FaGraduationCap, FaFileAlt, FaClock, FaChartLine }')
s=s.replace('getEmployeeById, removeCompanyName','getEmployeeById, removeCompanyName, getEmployeeAttendance')
s=s.replace('import EmployeeProfileInformation from','import EmployeeProfileOverview from "../../components/EmployeeProfileOverview";\nimport "../../styles/profileReferenceLayout.css";\nimport {normalizeCollection} from "../../utils/employeeCollection";\nimport EmployeeProfileInformation from')
s=s.replace('  const [showAttendance,setShowAttendance]=useState(false);','  const [showAttendance,setShowAttendance]=useState(false);\n  const [monthly,setMonthly]=useState(null);\n  const [monthlyError,setMonthlyError]=useState("");\n  const canViewAttendance=can("attendance","view");\n  useEffect(()=>{document.body.classList.add("e2e-profile-reference");return()=>document.body.classList.remove("e2e-profile-reference")},[]);\n  useEffect(()=>{let active=true;setMonthly(null);setMonthlyError("");if(!employee?.id||!canViewAttendance)return;const now=new Date();const ymd=d=>new Intl.DateTimeFormat("en-CA",{timeZone:"America/New_York",year:"numeric",month:"2-digit",day:"2-digit"}).format(d);const end=ymd(now),start=end.slice(0,7)+"-01";getEmployeeAttendance(employee.id,{start_date:start,end_date:end,limit:100}).then(r=>{if(active)setMonthly(r)}).catch(()=>{if(active)setMonthlyError("Attendance summary could not be loaded.")});return()=>{active=false}},[employee?.id,canViewAttendance,attendanceRevision]);')
# attendanceRevision declaration must precede its effect dependency evaluation.
s=s.replace('  const [monthly,setMonthly]', '  const [attendanceRevision,setAttendanceRevision]=useState(0);\n  const [monthly,setMonthly]',1)
s=s.replace('  const [attendanceRevision,setAttendanceRevision]=useState(0);\n  const [assigning', '  const [assigning')
s=s.replace("className='e2e_record_page e2e_record_blue'", "className='e2e_record_page e2e_record_blue reference-profile-page'")
start=s.index('      <header className="e2e_record_hero">')
end=s.index('      {error &&',start)
s=s[:start]+'''      <header className="e2e_record_hero reference-profile-hero"><div className="reference-person"><div className="e2e_record_avatar">{employee.profile_photo_url?<img src={employee.profile_photo_url} alt={employee.legal_name||"Employee"}/>:<FaUser/>}<i aria-hidden="true"/></div><div className="reference-person-copy"><div className="reference-name-line"><h1>{employee.legal_name||[employee.firstname,employee.lastname].filter(Boolean).join(" ")}</h1><strong className="reference-status">{employee.user_status|| (employee.user_id?"Assigned":"Not Assigned")}</strong></div><h2>{employee.position_name||employee.position||employee.role||"Position not assigned"}</h2><div className="reference-contact-line"><span><FaEnvelope/>{normalizeCollection(employee.collection).email||employee.payroll_email||"Email not provided"}</span><span><FaPhone/>{employee.contact_info||"Phone not provided"}</span><span><FaMapMarkerAlt/>{employee.payroll_profile?.location||employee.address||"Location not provided"}</span><span><FaCalendarAlt/>Joined {employee.date_of_joining||employee.joining_date||"Not recorded"}</span></div></div></div>
      {isOwn&&canViewAttendance?<EmployeeAttendanceSwitch compact employeeCode={employee.employee_id} onViewAttendance={()=>setShowAttendance(true)} onChanged={()=>setAttendanceRevision(n=>n+1)}/>:canViewAttendance?<section className="reference-today-card"><h2>Attendance (Today)</h2><p>View this employee's attendance records.</p><button type="button" onClick={()=>setShowAttendance(true)}>View Attendance</button></section>:null}</header>
      <nav className="employee-profile-actions reference-profile-tabs" aria-label="Profile sections"><a className="active" href="#profile-overview"><FaHome/>Overview</a><a href="#profile-details"><FaUser/>Personal</a><a href="#profile-employment"><FaBriefcase/>Employment</a><a href="#profile-projects"><FaBriefcase/>Projects</a><a href="#profile-performance"><FaChartLine/>Performance</a><button type="button" onClick={()=>setShowAttendance(value=>!value)} aria-expanded={showAttendance}><FaClock/>Time Tracking</button><a href="#profile-education"><FaGraduationCap/>Education</a><a href="#profile-documents"><FaFileAlt/>Documents</a><a href="#profile-activity"><FaCalendarAlt/>Activity</a></nav>
      <EmployeeProfileOverview employee={employee} attendance={monthly} attendanceError={monthlyError} canViewAttendance={canViewAttendance}/>
''' + s[end:]
s=s.replace('canManageDocuments={can("employees","edit")&&scope("employees")==="ALL"}/>', 'canManageDocuments={can("employees","edit")&&scope("employees")==="ALL"} overview={<EmployeeProfileOverview details employee={employee} attendance={monthly} attendanceError={monthlyError} canViewAttendance={canViewAttendance}/>}/>')
p.write_text(s,encoding='utf-8')
p=root/'src/components/EmployeeProfileInformation.js';s=p.read_text(encoding='utf-8')
s=s.replace('"profile-documents":"documents"','"profile-documents":"documents","profile-employment":"employment"')
s=s.replace('employee,canEdit,onEdit,canManageDocuments,onSaved})','employee,canEdit,onEdit,canManageDocuments,onSaved,overview})')
s=s.replace('<div className="profile-information-layout"><Card id="profile-completion"','<div className="profile-information-layout"><Card id="profile-completion"')
# Keep the completion card and all section editors, but CSS orders them into the reference layout.
old='[["Full Name",employee.legal_name||[employee.firstname,employee.lastname].filter(Boolean).join(" ")],["Employee ID",employee.employee_id],["Personal Email",c.email||employee.payroll_email],["Phone Number",employee.contact_info],["Date of Birth",employee.birthdate==="0000-00-00"?"":employee.birthdate],["Gender",employee.gender],["Permanent Address",employee.address],["Current Address",c.current_address],["Facebook Profile",c.facebook_profile],["Joining Date",employee.date_of_joining],["Role",employee.role],["Department",p.department],["Work Location",p.location]]'
new='[["Full Name",employee.legal_name||[employee.firstname,employee.lastname].filter(Boolean).join(" ")],["Personal Email",c.email||employee.payroll_email],["Phone Number",employee.contact_info],["Date of Birth",employee.birthdate==="0000-00-00"?"":employee.birthdate],["Gender",employee.gender],["Permanent Address",employee.address],["Current Address",c.current_address],["Facebook Profile",c.facebook_profile]]'
s=s.replace(old,new)
marker=' <Card id="profile-family"'
insert=''' <Card id="profile-employment" title="Employment Details" icon={<FaBriefcase/>}><Details rows={[["Employee ID",employee.employee_id],["Department",p.department],["Position",employee.position_name||employee.position||employee.role],["Joining Date",employee.date_of_joining||employee.joining_date],["Employment Type",employee.employment_type||p.employment_type],["Reporting Manager",employee.reporting_manager||p.reporting_manager],["Work Location",p.location],["Status",employee.user_status|| (employee.user_id?"Assigned":"Not Assigned")]]}/></Card>
 <Card id="profile-skills" title="Skills" icon={<FaCertificate/>}><div className="reference-skills-tags">{[...new Set(c.education.map(row=>row.branch).concat(c.certifications.map(row=>row.name)).filter(Boolean))].map(skill=><span key={skill}>{skill}</span>)}</div><h3>Qualifications & Certifications</h3><p>{c.education.length} qualifications · {c.certifications.length} certifications</p><a href="#profile-certifications">View / update certifications</a><p className="reference-skills-note">Skill proficiency ratings have not been recorded.</p></Card>
 {overview}
'''
s=s.replace(marker,insert+marker)
# Only permission holders can edit protected employment details. Its modal uses full administrative editor.
s=s.replace('context.canEdit&&key&&','context.canEdit&&key&&(key!=="employment"||context.canManageDocuments)&&')
s=s.replace('editSection={key}', 'editSection={key==="employment"?"all":key}')
p.write_text(s,encoding='utf-8')
# Header brand is rendered accessibly and only displayed in the scoped reference layout.
p=root/'src/pages/Dashboard/Navbar.js';s=p.read_text(encoding='utf-8');s=s.replace('      <div>\n        <h2 className="e2e_navbar_title">','      <div className="reference-header-brand"><img src="/logo.png" alt="E2E Tracking Services"/><div><strong>E2E TRACKING</strong><small>SERVICES</small></div></div>\n      <div className="e2e_navbar_page_title">\n        <h2 className="e2e_navbar_title">');p.write_text(s,encoding='utf-8')